<?php

/**
 *
 * @copyright  2010-2022 (2016-2022) izend.org
 * @version    27 (6)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<span id="node_hidy" class="hidy"></span>
<div class="form-group">
<?php echo $inlanguages; ?>
</div>
<div id="node">
<div class="form-group">
<label for="node_title">Titre</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="node_title" id="node_title" size="40" maxlength="100" value="<?php if ($node_title): ?><?php echo htmlspecialchars($node_title, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return submitonenter(event, 'node_edit')"/>
</div>
</div>
<div class="form-group<?php if ($missing_node_name or $bad_node_name): ?> has-error<?php endif; ?>">
<label for="node_name">URL</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="node_name" id="node_name" size="40" maxlength="100" value="<?php if ($node_name): ?><?php echo htmlspecialchars($node_name, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return focusonenter(event, 'node_title')"/>
</div>
</div>
<div class="form-group">
<label for="node_abstract">Extrait</label>
<div class="form-inline-auto">
<textarea class="form-control" name="node_abstract" id="node_abstract" cols="80" rows="3"><?php if ($node_abstract): ?><?php echo htmlspecialchars($node_abstract, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?></textarea>
</div>
</div>
<div class="form-group">
<label for="node_cloud">Nuage</label>
<div class="form-inline-auto">
<textarea class="form-control" name="node_cloud" id="node_cloud" cols="80" rows="2"><?php if ($node_cloud): ?><?php echo htmlspecialchars($node_cloud, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?></textarea>
</div>
</div>
<div class="form-group">
<label for="node_image">Image</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="node_image" id="node_image" size="40" maxlength="200" value="<?php if ($node_image): ?><?php echo htmlspecialchars($node_image, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>"/>
</div>
</div>
<fieldset>
<legend>Options</legend>
<div class="form-group form-inline">
<div class="form-group checkbox-group">
<div class="checkbox-inline">
<label for="node_visits"><input id="node_visits" name="node_visits" type="checkbox"<?php if ($node_visits): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_visits">visites</span></label>
</div>
<div class="checkbox-inline">
<label for="node_comment"><input id="node_comment" name="node_comment" type="checkbox"<?php if ($node_comment): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_comment">commenter</span></label>
</div>
<div class="checkbox-inline">
<label for="node_morecomment"><input id="node_morecomment" name="node_morecomment" type="checkbox"<?php if ($node_morecomment): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_morecomment">commenter+</span></label>
</div>
<div class="checkbox-inline">
<label for="node_vote"><input id="node_vote" name="node_vote" type="checkbox"<?php if ($node_vote): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_vote">vote</span></label>
</div>
<div class="checkbox-inline">
<label for="node_morevote"><input id="node_morevote" name="node_morevote" type="checkbox"<?php if ($node_morevote): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_morevote">vote+</span></label>
</div>
</div>
<div class="form-group checkbox-group">
<div class="checkbox-inline">
<label for="node_ilike"><input id="node_ilike" name="node_ilike" type="checkbox"<?php if ($node_ilike): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_ilike">facebook</span></label>
</div>
<div class="checkbox-inline">
<label for="node_tweet"><input id="node_tweet" name="node_tweet" type="checkbox"<?php if ($node_tweet): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_tweet">twitter</span></label>
</div>
<div class="checkbox-inline">
<label for="node_linkedin"><input id="node_linkedin" name="node_linkedin" type="checkbox"<?php if ($node_linkedin): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_linkedin">linkedin</span></label>
</div>
<div class="checkbox-inline">
<label for="node_pinit"><input id="node_pinit" name="node_pinit" type="checkbox"<?php if ($node_pinit): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_pinit">pinit</span></label>
</div>
<div class="checkbox-inline">
<label for="node_whatsapp"><input id="node_whatsapp" name="node_whatsapp" type="checkbox"<?php if ($node_whatsapp): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_whatsapp">whatsapp</span></label>
</div>
</div>
</div>
</fieldset>
<div class="form-group">
<button type="submit" class="btn <?php if ($missing_node_name or $bad_node_name): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="node_edit" id="node_edit">Éditer</button>
</div>
</div>
</form>
<?php head('javascript', 'js.cookie'); ?>
<script>
if (Cookies.get('hidenode') == 1) {
	$('#node').hide();
}
$('#node_hidy').click(function() {
	$('#node').toggle();
	Cookies.set('hidenode', $('#node').is(':hidden') ? 1 : 0, { path: '/', sameSite: 'lax' });
});
</script>
<?php
$focus=false;
if ($missing_node_name or $bad_node_name) {
	 $focus='#node_name';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
<?php if ($content_editor): ?>
<h4>Contenu</h4>
<?php echo $content_editor; ?>
<?php endif; ?>
