<?php

/**
 *
 * @copyright  2010-2013 (2016) izend.org
 * @version    16 (1)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<h3><?php echo htmlspecialchars($site_title ? $site_title : $sitename, ENT_COMPAT, 'UTF-8'); ?></h3>
<form method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<?php if ($confirm_delete_thread): ?>
<input name="old_thread_number" type="hidden" value="<?php echo $old_thread_number; ?>" />
<?php endif; ?>
<div class="form-group">
<?php echo $inlanguages; ?>
</div>
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn <?php if ($missing_new_thread_title or $missing_new_thread_name or $bad_new_thread_name or $bad_new_thread_number): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="thread_create" id="thread_create">Ajouter</button>
<span class="form-control-static">le fil</span>
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="new_thread_title" id="new_thread_title" size="30" maxlength="100" placeholder="Titre" value="<?php echo htmlspecialchars($new_thread_title, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'new_thread_number')" />
</div>
<div class="form-group form-inline-auto">
<span class="form-control-static">#</span>
<input type="text" class="form-control" name="new_thread_number" id="new_thread_number" size="2" maxlength="3" value="<?php echo htmlspecialchars($new_thread_title, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'thread_create')" />
<span class="form-control-static">type</span>
<select class="form-control" name="new_thread_type" size="1">
<option value="thread"<?php if ($new_thread_type == 'thread'): ?> selected="selected"<?php endif; ?>>Fil</option>
<?php foreach ($supported_threads as $type): ?>
<?php if ($type == 'folder'): ?>
<option value="folder"<?php if ($new_thread_type == 'folder'): ?> selected="selected"<?php endif; ?>>Dossier</option>
<?php elseif ($type == 'story'): ?>
<option value="story"<?php if ($new_thread_type == 'story'): ?> selected="selected"<?php endif; ?>>Article</option>
<?php elseif ($type == 'book'): ?>
<option value="book"<?php if ($new_thread_type == 'book'): ?> selected="selected"<?php endif; ?>>Manuel</option>
<?php elseif ($type == 'rss'): ?>
<option value="rss"<?php if ($new_thread_type == 'rss'): ?> selected="selected"<?php endif; ?>>RSS</option>
<?php elseif ($type == 'newsletter'): ?>
<option value="newsletter"<?php if ($new_thread_type == 'newsletter'): ?> selected="selected"<?php endif; ?>>Infolettre</option>
<?php endif; ?>
<?php endforeach; ?>
</select>
</div>
</div>
<?php if ($thread_list): ?>
<fieldset>
<legend>Catalogue</legend>
<div class="form-group">
<?php
foreach ($thread_list as $i => $tr):
	extract($tr);	/* pos, thread_id, thread_title, thread_number, thread_url */
	$thread_url .= '?' . 'clang=' . $clang;
?>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control input-sm" name="p[<?php echo $i; ?>]" size="2" maxlength="3" value="<?php echo $pos; ?>" />
</div>
<span class="form-control-static">
<a href="<?php echo $thread_url; ?>" title="<?php echo $thread_id; ?>"><?php echo $thread_title ? htmlspecialchars($thread_title, ENT_COMPAT, 'UTF-8') : $thread_id; ?></a>
</span>
</div>
<?php endforeach; ?>
</div>
</fieldset>
<?php if ($confirm_delete_thread): ?>
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn btn-default" name="thread_canceldelete" id="thread_canceldelete">Annuler</button>
<span class="form-control-static">ou</span>
<button type="submit" class="btn btn-warning" name="thread_confirmdelete" id="thread_confirmdelete">Confirmer</button>
</div>
<div class="form-group">
<span class="form-control-static">la suppression du fil <strong><?php echo $old_thread_number; ?></strong></span>
</div>
</div>
<?php else: ?>
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn btn-default" name="threadlist_reorder" id="threadlist_reorder">Trier</button>
<span class="form-control-static">le contenu</span>
</div>
<div class="form-group">
<span class="form-control-static">ou</span>
</div>
<div class="form-group form-inline-auto">
<button type="submit" class="btn <?php if ($missing_old_thread_number or $bad_old_thread_number): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="thread_delete" id="thread_delete">Supprimer</button>
<span class="form-control-static">le fil #</span>
<input type="text" class="form-control" name="old_thread_number" id="old_thread_number" size="2" maxlength="3" placeholder="" value="<?php echo htmlspecialchars($old_thread_number, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'thread_delete')" />
</div>
</div>
<?php endif; ?>
<?php endif; ?>
</form>
<?php
$focus=false;
if ($missing_new_thread_title or $missing_new_thread_name or $bad_new_thread_name) {
	 $focus='#new_thread_title';
}
else if ($bad_new_thread_number) {
	$focus='#new_thread_number';
}
else if ($missing_old_thread_number or $bad_old_thread_number) {
	$focus='#old_thread_number';
}
else if ($confirm_delete_thread) {
	$focus='#old_thread_number';
}
?>
<?php if ($focus): ?>
<?php head('javascript', 'jquery.scrollTo', 'screen'); ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus(); $.scrollTo('<?php echo $focus; ?>', {offset: -200}); });
</script>
<?php endif; ?>
