<?php

/**
 *
 * @copyright  2010-2018 (2016) izend.org
 * @version    8 (2)
 * @link       http://www.izend.org
 */
?>
<?php $with_search=false; ?>
<?php $with_headline=false; ?>
<?php $type='standard'; ?>
<?php
switch($type) {
	case 'static':
		$navbar='navbar-static-top';
		$container='container';
		break;
	case 'fixed':
		$navbar='navbar-fixed-top';
		$container='container';
		$css= <<<_SEP_
body {
	padding-top: 70px;
}
_SEP_;

		head('style', $css, 'screen');
		break;
	default:
		$navbar='navbar-standard-top';
		$container='container-fluid';
		$css= <<<_SEP_
body {
	padding-top: 20px;
}
_SEP_;

		head('style', $css, 'screen');
		break;
}
?>
<?php if (!empty($consent)): ?>
<?php echo $consent; ?>
<?php endif; ?>
<nav class="navbar navbar-default <?php echo $navbar; ?>">
<div class="<?php echo $container; ?>">
<div class="navbar-header">
<?php if (!empty($menu) or !empty($languages) or !empty($donate) or ($with_search and !empty($search)) or ($with_headline and !empty($headline))): ?>
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main" aria-expanded="false">
<span class="sr-only">Navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<?php endif; ?>
<?php echo $logo; ?>
</div>
<?php if (!empty($menu) or !empty($languages) or !empty($donate) or ($with_search and !empty($search)) or ($with_headline and !empty($headline))): ?>
<div class="collapse navbar-collapse" id="navbar-main">
<?php if (!empty($menu)): ?>
<?php echo $menu; ?>
<?php endif; ?>
<?php if (!empty($languages) or !empty($donate) or ($with_search and !empty($search)) or ($with_headline and !empty($headline))): ?>
<?php if ($with_search): ?>
<?php if (!empty($search)): ?>
<div class="navbar-form navbar-right">
<?php echo $search; ?>
</div>
<?php endif; ?>
<?php endif; ?>
<?php if ($with_headline): ?>
<?php if (!empty($headline)): ?>
<div class="navbar-text navbar-right">
<?php echo $headline; ?>
</div>
<?php endif; ?>
<?php endif; ?>
<div class="navbar-right">
<?php if (!empty($donate)): ?>
<?php echo $donate; ?>
<?php endif; ?>
<?php if (!empty($languages)): ?>
<?php echo $languages; ?>
<?php endif; ?>
</div>
<?php endif; ?>
</div>
<?php endif; ?>
</div>
</nav>
