<?php

/**
 *
 * @copyright  2010-2026 (2016-2026) izend.org
 * @version    15 (5)
 * @link       http://www.izend.org
 */
?>
<?php if ($ilike or $tweetit or $linkedin or $pinit or $whatsapp): ?>
<ul class="besocial <?php echo $sharemode; ?> hidden-print">
<?php if ($ilike): ?>
<li class="facebook">
<?php echo $ilike; ?>
</li>
<?php endif; ?>
<?php if ($tweetit): ?>
<li class="x_twitter">
<?php echo $tweetit; ?>
</li>
<?php endif; ?>
<?php if ($linkedin): ?>
<li class="linkedin">
<?php echo $linkedin; ?>
</li>
<?php endif; ?>
<?php if ($pinit): ?>
<li class="pinterest">
<?php echo $pinit; ?>
</li>
<?php endif; ?>
<?php if ($whatsapp): ?>
<li class="whatsapp">
<?php echo $whatsapp; ?>
</li>
<?php endif; ?>
</ul>
<script>
$(document).ready(function() {$('.besocial').show();});
</script>
<?php endif; ?>
