<?php

/**
 *
 * @copyright  2010-2014 (2016) izend.org
 * @version    7 (1)
 * @link       http://www.izend.org
 */
?>
<div id="bookpage">
<?php if ($vote): ?>
<?php echo $vote; ?>
<?php endif; ?>
<?php if ($visits): ?>
<?php echo $visits; ?>
<?php endif; ?>
<h3><?php echo htmlspecialchars($page_title ? $page_title : $page_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<?php if ($next_page_url or $prev_page_url): ?>
<p>
<?php if ($prev_page_url): ?>
&larr;&nbsp;<a href="<?php echo $prev_page_url; ?>"><?php echo htmlspecialchars($prev_page_label, ENT_COMPAT, 'UTF-8'); ?></a>
<?php endif; ?>
<?php if ($next_page_url and $prev_page_url): ?>
&nbsp;|&nbsp;
<?php endif; ?>
<?php if ($next_page_url): ?>
<a href="<?php echo $next_page_url; ?>"><?php echo htmlspecialchars($next_page_label, ENT_COMPAT, 'UTF-8'); ?></a>&nbsp;&rarr;
<?php endif; ?>
</p>
<?php endif; ?>
<?php if ($page_contents): ?>
<?php echo $page_contents; ?>
<?php endif; ?>
<?php if ($besocial): ?>
<?php echo $besocial; ?>
<?php endif; ?>
<?php if ($page_comment): ?>
<?php echo $page_comment; ?>
<?php endif; ?>
</div>
