<?php

/**
 *
 * @copyright  2010-2017 (2017) izend.org
 * @version    4 (2)
 * @link       http://www.izend.org
 */
?>
<?php global $supported_languages; ?>
<div class="btn-group btn-group-sm">
<?php foreach ($supported_languages as $lang): ?>
<?php if ($lang == 'fr'): ?>
<a class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" href="?clang=fr">Français</a>
<?php elseif ($lang == 'en'): ?>
<a class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" href="?clang=en">English</a>
<?php elseif ($lang == 'de'): ?>
<a class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" href="?clang=de">Deutsch</a>
<?php elseif ($lang == 'it'): ?>
<a class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" href="?clang=it">Italiano</a>
<?php elseif ($lang == 'es'): ?>
<a class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" href="?clang=es">Español</a>
<?php elseif ($lang == 'ru'): ?>
<a class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" href="?clang=ru">Pусский</a>
<?php endif; ?>
<?php endforeach; ?>
</div>
