<?php

/**
 *
 * @copyright  2010-2013 (2016) izend.org
 * @version    3 (1)
 * @link       http://www.izend.org
 */
?>
<?php global $supported_languages; ?>
<div class="btn-group btn-group-sm">
<?php foreach ($supported_languages as $lang): ?>
<?php if ($lang == 'fr'): ?>
<button type="submit" class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" name="<?php echo $lang; ?>">Français</button>
<?php elseif ($lang == 'en'): ?>
<button type="submit" class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" name="<?php echo $lang; ?>">English</button>
<?php elseif ($lang == 'de'): ?>
<button type="submit" class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" name="<?php echo $lang; ?>">Deutsch</button>
<?php elseif ($lang == 'it'): ?>
<button type="submit" class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" name="<?php echo $lang; ?>">Italiano</button>
<?php elseif ($lang == 'es'): ?>
<button type="submit" class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" name="<?php echo $lang; ?>">Español</button>
<?php elseif ($lang == 'ru'): ?>
<button type="submit" class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" name="<?php echo $lang; ?>">Pусский</button>
<?php elseif ($lang == 'ar'): ?>
<button type="submit" class="btn <?php if ($lang == $clang): ?>btn-primary<?php else: ?>btn-default<?php endif; ?>" name="<?php echo $lang; ?>">عربي</button>
<?php endif; ?>
<?php endforeach; ?>
</div>
