<?php

/**
 *
 * @copyright  2010-2013 (2016) izend.org
 * @version    6 (1)
 * @link       http://www.izend.org
 */
?>
<ul class="nav navbar-nav">
<?php if ($fr_page): ?>
<li><a href="<?php echo $fr_page; ?>" title="Version française"><span>Français</span></a></li>
<?php endif; ?>
<?php if ($en_page): ?>
<li><a href="<?php echo $en_page; ?>" title="English version"><span>English</span></a></li>
<?php endif; ?>
<?php if ($de_page): ?>
<li><a href="<?php echo $de_page; ?>" title="Deutsch Version"><span>Deutsch</span></a></li>
<?php endif; ?>
<?php if ($it_page): ?>
<li><a href="<?php echo $it_page; ?>" title="Versione italiana"><span>Italiano</span></a></li>
<?php endif; ?>
<?php if ($es_page): ?>
<li><a href="<?php echo $es_page; ?>" title="Versión española"><span>Español</span></a></li>
<?php endif; ?>
<?php if ($ru_page): ?>
<li><a href="<?php echo $ru_page; ?>" title="Pусская версия"><span>Pусский</span></a></li>
<?php endif; ?>
</ul>
