<?php

/**
 *
 * @copyright  2010-2020 (2016) izend.org
 * @version    11 (2)
 * @link       http://www.izend.org
 */
?>
<?php $with_title=true; ?>
<?php $with_search=true; ?>
<?php if (($with_title and !empty($title)) or ($with_search and !empty($search)) or !empty($summary) or !empty($cloud)): ?>
<div id="sidebar">
<?php if ($with_title): ?>
<?php if (!empty($title)): ?>
<?php echo $title; ?>
<?php endif; ?>
<?php endif; ?>
<?php if ($with_search): ?>
<?php if (!empty($search)): ?>
<?php echo $search; ?>
<?php endif; ?>
<?php endif; ?>
<?php if (!empty($summary)): ?>
<ol id="summary" class="list-unstyled">
<?php foreach ($summary as $s): ?>
<?php extract($s);	/* summary_page_id summary_page_title summary_page_url */ ?>
<li><a href="<?php echo $summary_page_url; ?>"><?php echo htmlspecialchars($summary_page_title ? $summary_page_title : $summary_page_id, ENT_NOQUOTES, 'UTF-8', false); ?></a></li>
<?php endforeach; ?>
</ol>
<?php endif; ?>
<?php if (!empty($cloud)): ?>
<?php head('javascript', 'js.cookie'); ?>
<span class="hidy"></span>
<?php echo $cloud; ?>
<script>
if (Cookies.get('hidesidecloud') == 1) {
	$('#sidebar .cloud').hide();
}
$('#sidebar .hidy').click(function() {
	$('#sidebar .cloud').toggle();
	Cookies.set('hidesidecloud', $('#sidebar .cloud').is(':hidden') ? 1 : 0, { path: '/', sameSite: 'lax' });
});
</script>
<?php endif; ?>
</div>
<?php endif; ?>
