<?php

/**
 *
 * @copyright  2019-2020 (2019-2020) izend.org
 * @version    4 (3)
 * @link       http://www.izend.org
 */
?>
<?php if (!$with_fileupload): ?>
<form enctype="multipart/form-data" method="post" class="compact noprint">
<input type="hidden" name="upload_token" value="<?php echo $token; ?>" />
<?php if (!empty($maxfilesize)): ?>
<input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $maxfilesize; ?>" />
<?php endif; ?>
<?php endif; ?>
<?php if ($with_drop): ?>
<div id="upload_droparea">
<?php if (!$with_upload): ?>
<span id="upload_status">
<?php endif; ?>
<span class="glyphicon glyphicon-download-alt"></span>
<?php if (!$with_upload): ?>
</span>
<?php endif; ?>
</div>
<?php endif; ?>
<div class="form-group">
<input type="file" name="upload_file" id="upload_file" title=""<?php if ($filetypes): ?> accept="<?php echo implode(',', $filetypes); ?>"<?php endif; ?> />
</div>
<div class="form-group">
<?php if ($with_upload): ?>
<?php extract($errors); ?>
<?php extract($infos); ?>
<button type="submit" class="btn <?php if ($missing_file or $bad_file or $bad_name or $bad_size or $bad_copy or $copy_error): ?>btn-danger<?php elseif ($file_copied): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="upload_put" id="upload_put"><?php echo $upload_put_value; ?></button>
<?php endif; ?>
<?php if ($with_upload and $with_fileupload): ?>
<span class="form-control-static"><span id="upload_status"></span></span>
<?php endif; ?>
</div>
<?php if (!$with_fileupload): ?>
</form>
<?php endif; ?>
<script>
(function() {
	const file=$('#upload_file');

	file.css({ position: 'absolute', left: '-9999px' });

<?php if ($with_upload): ?>
	const upload=$('#upload_put');

	function enableupload() {
		upload.on('click', function(e) { e.preventDefault(); file.click(); });
	}

	function disableupload() {
		upload.off('click');
	}

	enableupload();
<?php endif; ?>

<?php if ($with_fileupload): ?>
	const status=$('#upload_status');

	function showstatus(ok) {
<?php if ($with_upload): ?>
		upload.attr('class', 'btn btn-' + (ok ? 'success' : 'danger'));
<?php if ($with_fileupload): ?>
		status.text('');
<?php endif; ?>
		enableupload();
<?php elseif ($with_drop): ?>
		status.html('<span class="glyphicon glyphicon-download-alt text-' + (ok ? 'success' : 'danger') + '"></span>');
<?php endif; ?>
	}
<?php endif; ?>

	file.change(function() {
		if (file.val()) {
<?php if ($with_upload): ?>
			disableupload();
<?php endif; ?>
<?php if ($with_fileupload): ?>
			uploadfile(this.files[0]);
<?php else: ?>
			upload.click();
<?php endif; ?>
		}
	});

<?php if ($with_fileupload): ?>
	function uploadfile(fd) {
		const reader = new FileReader();
		const size = 1000000;

		var offset = 0, progress = 0, blob;

<?php if ($filetypes): ?>
		var filetypes=[<?php foreach ($filetypes as $i => $type): ?><?php if ($i > 0): ?>,<?php endif; ?>'<?php echo $type; ?>'<?php endforeach; ?>];
<?php endif; ?>

		function uploadslice() {
<?php if ($with_upload): ?>
			upload.attr('class', 'btn btn-default');
<?php endif; ?>
<?php if ($with_fileupload): ?>
			status.text(progress + '%');
<?php endif; ?>
			blob = fd.slice(offset, offset + size);
			reader.readAsDataURL(blob);
		}

		reader.onloadend = function(event) {
			$.post('<?php echo $upload_url; ?>', {file_token: '<?php echo $token; ?>', file_name: fd.name, file_size: fd.size, file_type: fd.type, file_offset: offset, file_data: event.target.result})
				.done(() => {
					offset += blob.size;
					progress = Math.floor((offset / fd.size ) * 100);

					if (progress < 100)
						uploadslice();
					else
						showstatus(true);
				})
				.fail(() => showstatus(false));
		};

<?php if ($filetypes or $maxfilesize): ?>
<?php if ($filetypes and $maxfilesize): ?>
		if ($.inArray(fd.type, filetypes) != -1 && fd.size <= <?php echo $maxfilesize; ?>) {
			uploadslice();
		}
<?php elseif ($filetypes): ?>
		if ($.inArray(fd.type, filetypes) != -1) {
			uploadslice();
		}
<?php elseif ($maxfilesize): ?>
		if (fd.size <= <?php echo $maxfilesize; ?>) {
			uploadslice();
		}
<?php endif; ?>
		else {
			showstatus(false)
		}
<?php else: ?>
		uploadslice();
<?php endif; ?>
	}

<?php if ($with_drop): ?>
	const droparea=$('#upload_droparea');

	droparea.on('click', function(e) { file.click(); });

	droparea.on('drop', function(e) {
		var dt = e.originalEvent.dataTransfer;

		e.preventDefault();

		if ($.inArray('Files', dt.types) != -1) {
			uploadfile(dt.files[0]);
		}
	});

	droparea.on('dragenter', function(e) {
		var dt = e.originalEvent.dataTransfer;

		if ($.inArray('Files', dt.types) != -1) {
			e.preventDefault();
		}
	});

	droparea.on('dragleave', function(e) {
		e.preventDefault();
	});

	droparea.on('dragover', function(e) {
		var dt = e.originalEvent.dataTransfer;

		e.preventDefault();

		dt.dropEffect = $.inArray('Files', dt.types) != -1 ? 'copy' : 'none';
	});
<?php endif; ?>
<?php endif; ?>
})();
</script>
