<?php

/**
 *
 * @copyright  2016-2019 (2016) izend.org
 * @version    7 (2)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form method="post">
<input type="hidden" name="analytics_token" value="<?php echo $token; ?>" />
<div class="form-group<?php if ($missing_url or $bad_url): ?> has-error<?php endif; ?>">
<label for="analytics_url">URL</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="analytics_url" id="analytics_url" size="50" maxlength="200" value="<?php echo htmlspecialchars($url, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'analytics_draw')" />
</div>
</div>
<div class="form-group<?php if ($missing_period or $bad_period): ?> has-error<?php endif; ?>">
<label for="analytics_period">Options</label>
<?php if ($with_period): ?>
<div class="form-group-inline">
<label class="radio-inline"><input type="radio" name="analytics_period" value="1weekago" title="1 semaine"<?php if ($period == '1weekago'): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;1&nbsp;semaine</span></label>
<label class="radio-inline"><input type="radio" name="analytics_period" value="2weeksago" title="2 semaines"<?php if ($period == '2weeksago'): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;2&nbsp;semaines</span></label>
</div>
<div class="form-group-inline">
<label class="radio-inline"><input type="radio" name="analytics_period" value="1monthago" title="1 mois"<?php if ($period == '1monthago'): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;1&nbsp;mois</span></label>
<label class="radio-inline"><input type="radio" name="analytics_period" value="3monthsago" title="3 mois"<?php if ($period == '3monthsago'): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;3&nbsp;mois</span></label>
<label class="radio-inline"><input type="radio" name="analytics_period" value="6monthsago" title="6 mois"<?php if ($period == '6monthsago'): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;6&nbsp;mois</span></label>
</div>
<div class="form-group-inline">
<label class="radio-inline"><input type="radio" name="analytics_period" value="1yearago" title="1 an"<?php if ($period == '1yearago'): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;1&nbsp;an</span></label>
</div>
<?php else: ?>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="analytics_startdate" id="analytics_startdate" size="10" placeholder="aaaa-mm-jj" value="<?php echo htmlspecialchars($start_date, ENT_COMPAT, 'UTF-8'); ?>" />
<span class="form-control-static hidden-xs">&rarr;</span>
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="analytics_enddate" id="analytics_enddate" size="10" placeholder="aaaa-mm-jj" value="<?php echo htmlspecialchars($end_date, ENT_COMPAT, 'UTF-8'); ?>" />
</div>
</div>
<?php head('javascript', 'jquery-ui'); ?>
<?php head('javascript', 'jquery.ui.datepicker-fr'); ?>
<?php head('stylesheet', 'jquery-ui', 'screen'); ?>
<script>
$('#analytics_startdate, #analytics_enddate').datepicker({dateFormat: 'yy-mm-dd', autoSize: true, showAnim: 'drop', showOn: 'both', buttonText: 'Calendrier', buttonImage: '/images/theme/edit/calendar.png', buttonImageOnly: true, maxDate: 'today', showOtherMonths: true, navigationAsDateFormat: true, prevText: 'MM', nextText: 'MM'});
</script>
<?php endif; ?>
<div class="form-group">
<label class="checkbox-inline">
<input type="checkbox" name="analytics_trendline"<?php if ($trendline): ?> checked="checked"<?php endif; ?> />&nbsp;<span class="btn_edit btn_chart" title="Avec tendance"></span>
</label>
</div>
</div>
<div class="form-group">
<button type="submit" class="btn <?php if ($internal_error or $missing_url or $bad_url): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="analytics_draw" id="analytics_draw">Tracer</button>
</div>
</form>
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.</p>
<?php endif; ?>
<?php
$focus=false;
if ($missing_url or $bad_url) {
	$focus='#analytics_url';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
<?php if ($data): ?>
<div id="traffic"></div>
<?php head('javascript', 'https://www.gstatic.com/charts/loader.js'); ?>
<script>
google.charts.load('current', {'packages':['corechart'], 'language': 'fr'});
google.charts.setOnLoadCallback(drawChart);

function drawChart() {
	var data = new google.visualization.DataTable();

	data.addColumn('date', 'Date');
	data.addColumn('number', 'Visites');
<?php $countmin=$data[0][1]; $countmax=0; ?>
	data.addRows([
<?php foreach ($data as $d): list($date, $count)=$d; $y=substr($date, 0, 4); $m=substr($date, 4, 2); $d=substr($date, 6, 2); ?>
<?php if ($count < $countmin) $countmin=$count; ?>
<?php if ($count > $countmax) $countmax=$count; ?>
		[new Date(<?php echo $y; ?>, <?php echo $m-1; ?>, <?php echo $d; ?>), <?php echo $count; ?>],
<?php endforeach; ?>
	]);
<?php
$minvalue=$countmin;
$d=$countmax-$countmin;
if ($d <= 5) {
	$maxvalue=$countmax+$d%2;
	$ticks=range($minvalue, $maxvalue, 1);
}
else if ($d <= 10) {
	$maxvalue=$countmax+$d%2;
	$ticks=range($minvalue, $maxvalue, 2);
}
else if ($d <= 50) {
	$maxvalue=$minvalue+5*ceil($d/5);
	$ticks=range($minvalue, $maxvalue, 5);
}
else {
	$maxvalue=false;
	$ticks=false;
}
?>
	var options = {
		title: '<?php echo number_format($visits, 0, ',', ' '); ?> visite<?php if ($visits > 1): ?>s<?php endif; ?> - min : <?php echo $countmin; ?> max : <?php echo $countmax; ?><?php if ($average !== false): ?> moy : <?php echo number_format($average, 1, ',' , ' '); ?><?php endif; ?>',
		hAxis: {
			format: 'd MMMM',
		},
		vAxis: {
			minValue: <?php echo $minvalue; ?>,
<?php if ($maxvalue): ?>
			maxValue: <?php echo $maxvalue; ?>,
<?php endif; ?>
<?php if ($ticks): ?>
			ticks:  [<?php echo implode(',', $ticks); ?>],
<?php endif; ?>
		},
		legend: {
			position: 'none',
		},
		lineWidth: 2,
		colors: ['#333333'],
<?php if ($trendline): ?>
		trendlines: {
			0: {
				lineWidth: 1,
				color: '#ec902d',
		        visibleInLegend: false,
		        tooltip: false,
			},
		},
<?php endif; ?>
	};

	var chart = new google.visualization.LineChart(document.getElementById('traffic'));

	google.visualization.events.addListener(chart, 'ready', function () {
		$('#traffic').append('<div class="download"><span class="glyphicon glyphicon-download" aria-hidden="true"></span><a href="' + chart.getImageURI() + '" download="trafic.png" title="">trafic.png</a></div>\n');
	});

	chart.draw(data, options);
}
</script>
<?php endif; ?>
