<?php

/**
 *
 * @copyright  2010-2021 (2021) izend.org
 * @version    16 (3)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<p>Votre site <b>iZend</b> est pratiquement fonctionnel.
Lisez les instructions suivantes, remplissez le formulaire et appuyez sur Configurer pour lancer le configurateur.</p>
<h6>Paramètres</h6>
<p>Entrez le nom du site, l'adresse d'email du webmestre et sélectionnez les langues gérées par le site.
Initialement, vous ne pourrez choisir que parmi les langues supportées par le noyau du logiciel.
Une fois le site configuré, vous pourrez facilement ajouter des contenus dans plusieurs autres langues.
Tous les paramètres du logiciel sont dans le dossier <i>includes</i>.
Le configurateur récrit les fichiers de configuration <i>config.inc</i>, <i>db.inc</i> et <i>aliases.inc</i> et les fichiers <i>sitemap.xml</i>, <i>robots.txt</i> et <i>.htaccess</i> dans le répertoire racine du site.</p>
<p>Pour plus de sécurité, vérifiez que l'accès aux fichiers de configuration est limité au serveur&nbsp;:</p>
<pre><code>$ cd <?php echo ROOT_DIR; ?>; sudo chgrp -R www-data .; chmod -R g+w .
$ cd <?php echo ROOT_DIR; ?>/includes; chmod 660 db.inc config.inc settings.inc aliases.inc paypal.inc</code></pre>
<p>NOTE&nbsp;: Le nom du groupe d'exécution du serveur est défini par la directive Group, généralement dans le fichier <i>/etc/apache2/apache2.conf</i>.</p>
<h6>Logo</h6>
<p>Le configurateur génère un logo à partir du nom du site et l'enregistre dans le fichier <i>sitelogo.png</i> dans le dossier <i>logos</i>.
Vous voudrez probablement le changer.</p>
<h6>Base de données</h6>
<p>iZend peut fonctionner sans une base de données.
Dans ce mode, vous pourrez toujours profiter de l'architecture du logiciel mais vous devrez rédiger les pages du site sans l'éditeur.
Optez pour cette configuration pour mettre en ligne un site avec des ressources limitées.
Notez que iZend peut occuper très peu de place sur disque.</p>
<p>Pour exploiter tout le potentiel d'iZend, vous devez disposer d'un serveur de bases de données.
Vous pouvez utiliser MySQL ou PostgreSQL.
Le configurateur peut créer une nouvelle base de données ou utiliser une base de données déjà existante.
<b>IMPORTANT</b>&nbsp;: Si la base de données est partagée, demandez au configurateur d'ajouter un préfixe aux noms des tables.
Dans tous les cas, utiliser un préfixe est plus prudent.</p>
<p>NOTE&nbsp;: Si vous développez le site en local avant de le mettre en ligne, ce qui est recommandé, utilisez les mêmes paramètres sur les deux serveurs.</p>
<h5>Configuration</h5>
<?php if ($bad_write_permission): ?>
<div class="alert alert-danger" role="alert">
<p>Le serveur n'est pas autorisé à modifier <?php if (count($bad_write_permission) > 1): ?>les dossiers ou les fichiers suivants<?php else: ?>le dossier ou le fichier suivant<?php endif; ?> dans le dossier <i><?php echo ROOT_DIR; ?></i>&nbsp;:
</p>
<ul class="list-unstyled">
<?php foreach ($bad_write_permission as $file): ?>
<li><i><?php echo $file; ?></i></li>
<?php endforeach; ?>
</ul>
</div>
<p>Pour modifier les droits d'accès, entrez les commande suivantes&nbsp;:</p>
<pre><code>$ cd <?php echo ROOT_DIR; ?><?php echo PHP_EOL; ?>
$ chmod g+w<?php foreach ($bad_write_permission as $fname) { echo ' ', $fname; }; ?><?php echo PHP_EOL; ?>
$ chgrp www-data<?php foreach ($bad_write_permission as $fname) { echo ' ', $fname; }; ?></code></pre>
<?php endif; ?>
<?php $nerrors=count(array_keys($errors, true, true)); ?>
<?php if ($nerrors > 0): ?>
<div class="alert alert-danger" role="alert">
<p>Le formulaire a <?php echo $nerrors; ?> erreur<?php if ($nerrors > 1): ?>s<?php endif; ?>.
Vérifiez vos réponses et relancez la configuration.</p>
</div>
<?php endif; ?>
<?php if ($internal_error): ?>
<div class="alert alert-danger" role="alert">
<p>La génération des fichiers de configuration a échoué.</p>
</div>
<?php endif; ?>
<?php if ($file_error): ?>
<div class="alert alert-danger" role="alert">
<p>L'écriture des fichiers de configuration a échoué.</p>
</div>
<?php endif; ?>
<form method="post">
<input type="hidden" name="configure_token" value="<?php echo $token; ?>" />
<div class="form-group<?php if ($missing_sitename): ?> has-error<?php endif; ?>">
<label for="configure_sitename">Quel est le nom du site&nbsp;?</label>
<span class="help-block">Spécifiez un nom de domaine sans le préfixer par <em>www</em>.</span>
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_sitename" id="configure_sitename" size="30" maxlength="40" value="<?php echo htmlspecialchars($sitename, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'configure_webmaster')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-globe"></span></span>
</div>
</div>
<?php if ($missing_sitename): ?>
<p class="text-danger">Entrez un nom de domaine tel que <em>izend.org</em>.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_webmaster): ?> has-error<?php endif; ?>">
<label for="configure_webmaster">Quelle est l'adresse d'email du webmestre&nbsp;?</label>
<span class="help-block">La page de contact envoie les messages à cette adresse.</span>
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_webmaster" id="configure_webmaster" size="30" maxlength="100" value="<?php echo htmlspecialchars($webmaster, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'configure_sitename')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
</div>
</div>
<?php if ($missing_webmaster): ?>
<p class="text-danger">Spécifiez une adresse d'email valide.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_content_languages): ?> has-error<?php endif; ?>">
<label>Dans quelles langues le contenu du site est-il rédigé&nbsp;?</label>
<span class="help-block">Vous pourrez toujours ajouter d'autres langues plus tard.</span>
<div class="form-group">
<?php foreach ($system_languages as $slang): ?><?php echo PHP_EOL; ?><label class="checkbox-inline"><input name="configure_content_languages[]" type="checkbox" value="<?php echo $slang; ?>" title="<?php echo $slang; ?>"<?php if (in_array($slang, $content_languages)): ?> checked="checked"<?php endif; ?>/>&nbsp;<span class="lang-<?php echo $slang; ?>" title="<?php echo $slang; ?>"><?php echo $slang; ?></span></label><?php endforeach; ?><?php echo PHP_EOL; ?>
</div>
<?php if ($missing_content_languages): ?>
<p class="text-danger">Choisissez au moins une langue pour le contenu du site.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($bad_default_language): ?> has-error<?php endif; ?>">
<label>Quelle est la langue par défaut&nbsp;?</label>
<div class="form-group">
<?php foreach ($system_languages as $slang): ?><?php echo PHP_EOL; ?><label class="radio-inline"><input name="configure_default_language" type="radio" value="<?php echo $slang; ?>" title="<?php echo $slang; ?>"<?php if ($slang == $default_language): ?> checked="checked"<?php endif; ?> />&nbsp;<span class="lang-<?php echo $slang; ?>" title="<?php echo $slang; ?>"><?php echo $slang; ?></span></label><?php endforeach; ?><?php echo PHP_EOL; ?>
</div>
<?php if ($bad_default_language): ?>
<p class="text-danger">Vous n'avez pas mentionné cette langue dans la liste précédente.</p>
<?php endif; ?>
</div>
<h6>Base de données</h6>
<?php if ($db_error): ?>
<div class="alert alert-danger" role="alert">
<p>La configuration de la base de données a échoué avec l'erreur&nbsp;:</p>
<p><?php echo htmlspecialchars($db_error); ?></p>
<?php if ($db_flag and !$db_reuse): ?>
<?php if ($db_type == 'mysql'): ?>
<p><b>IMPORTANT</b>&nbsp;: Avant de relancer la configuration, vous devez supprimer manuellement la BD <code><?php echo htmlspecialchars($db_name, ENT_COMPAT, 'UTF-8'); ?></code>
et les entrées pour l'utilisateur <code><?php echo $db_user; ?></code> dans les tables <i>user</i> et <i>db</i> de la BD <i>mysql</i>.
Terminez par l'exécution d'un ordre FLUSH PRIVILEGES.</p>
<?php elseif ($db_type == 'pgsql'): ?>
<p><b>IMPORTANT</b>&nbsp;: Avant de relancer la configuration, vous devez supprimer manuellement la BD <code><?php echo htmlspecialchars($db_name, ENT_COMPAT, 'UTF-8'); ?></code>
et le rôle <code><?php echo $db_user; ?></code>.</p>
<?php endif; ?>
<?php endif; ?>
</div>
<?php endif; ?>
<div class="form-group">
<label>Avez-vous un serveur de bases de données&nbsp;?</label>
<span class="help-block">Sans une base de données, les fonctionnalités seront plus limitées.</span>
<div class="form-group">
<label class="radio-inline"><input name="configure_db_flag" type="radio" value="yes"<?php if ($db_flag): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">oui</span></label>
<label class="radio-inline"><input name="configure_db_flag" type="radio" value="no"<?php if (!$db_flag): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">non</span></label>
</div>
<span class="help-block">Si vous n'utilisez pas de base de données, sautez les questions suivantes et appuyez juste sur Configurer.</span>
</div>
<div class="form-group<?php if ($bad_db_type): ?> has-error<?php endif; ?>">
<label>Utilisez-vous MySQL ou PostgreSQL&nbsp;?</label>
<div class="form-group">
<label class="radio-inline"><input name="configure_db_type" type="radio" value="mysql"<?php if ($db_type == 'mysql'): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">MySQL</span></label>
<label class="radio-inline"><input name="configure_db_type" type="radio" value="pgsql"<?php if ($db_type == 'pgsql'): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">PostgreSQL</span></label>
</div>
<?php if ($bad_db_type): ?>
<p class="text-danger">Cochez l'option MySQL ou l'option PostgreSQL.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_db_name or $bad_db_name): ?> has-error<?php endif; ?>">
<label for="configure_db_name">Quel est le nom de la base de données&nbsp;?</label>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="configure_db_name" id="configure_db_name" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_name, ENT_COMPAT, 'UTF-8'); ?>" />
</div>
<?php if ($missing_db_name or $bad_db_name): ?>
<p class="text-danger">Entrez de 2 à 30 caractères (lettre, chiffre ou souligné) en commençant par une lettre.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_db_host or $bad_db_host): ?> has-error<?php endif; ?>">
<label for="configure_db_host">Quel est le nom du serveur hôte de la base de données&nbsp;?</label>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="configure_db_host" id="configure_db_host" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_host, ENT_COMPAT, 'UTF-8'); ?>" />
</div>
<?php if ($missing_db_host or $bad_db_host): ?>
<p class="text-danger">Entrez un nom de serveur ou une adresse IP.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_db_user or $missing_db_password or $bad_db_user or $weak_db_password): ?> has-error<?php endif; ?>">
<label>Quels sont le nom et le mot de passe de l'utilisateur de la base de données&nbsp;?</label>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_db_user" id="configure_db_user" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_user, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'configure_db_password')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
</div>
</div>
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_db_password" id="configure_db_password" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_password, ENT_COMPAT, 'UTF-8'); ?>" autocomplete="off" onkeypress="return focusonenter(event, 'configure_db_user')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
</div>
</div>
</div>
<?php if ($missing_db_user and $missing_db_password): ?>
<p class="text-danger">Choisissez un identifiant pour l'utilisateur de la base de données et un mot de passe.</p>
<?php endif; ?>
<?php if ($missing_db_user or $bad_db_user): ?>
<p class="text-danger">Entrez un identifiant de 2 à 30 caractères (lettre, chiffre ou souligné) en commençant par une lettre.</p>
<?php endif; ?>
<?php if ($weak_db_password): ?>
<p class="text-danger">Entrez un mot de passe de 10 caractères avec au moins 2 majuscules, 2 minuscules, 2 chiffres et 2 caractères spéciaux ou effacez le champ pour laisser le système en choisir un.</p>
<?php endif; ?>
</div>
<div class="form-group">
<label>Utilisez-vous une base de données déjà existante&nbsp;?</label>
<div class="form-group">
<label class="radio-inline"><input name="configure_db_reuse" type="radio" value="yes"<?php if ($db_reuse): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">oui</span></label>
<label class="radio-inline"><input name="configure_db_reuse" type="radio" value="no"<?php if (!$db_reuse): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">non</span></label>
</div>
</div>
<div class="form-group<?php if ($missing_db_admin_user or $missing_db_admin_password): ?> has-error<?php endif; ?>">
<label>Si non, quels sont le nom et le mot de passe de l'administrateur du serveur de bases de données&nbsp;?</label>
<span class="help-block">Ces informations ne seront pas enregistrées.</span>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_db_admin_user" id="configure_db_admin_user" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_admin_user, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'configure_db_admin_password')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
</div>
</div>
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_db_admin_password" id="configure_db_admin_password" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_admin_password, ENT_COMPAT, 'UTF-8'); ?>" autocomplete="off" onkeypress="return focusonenter(event, 'configure_db_admin_user')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
</div>
</div>
</div>
<?php if ($missing_db_admin_user and $missing_db_admin_password): ?>
<p class="text-danger">Entrez l'identifiant de l'administrateur du serveur de bases de données suivi de son mot de passe.</p>
<?php else: ?>
<?php if ($missing_db_admin_user): ?>
<p class="text-danger">Entrez l'identifiant de l'administrateur du serveur de bases de données.</p>
<?php endif; ?>
<?php if ($missing_db_admin_password): ?>
<p class="text-danger">Entrez le mot de passe de l'administrateur du serveur de bases de données.</p>
<?php endif; ?>
<?php endif; ?>
</div>
<div class="form-group<?php if ($bad_db_prefix): ?> has-error<?php endif; ?>">
<label for="configure_db_prefix">Quel est le préfixe des tables&nbsp;?</label>
<span class="help-block">Un préfixe est nécessaire si la base de données est partagée.</span>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="configure_db_prefix" id="configure_db_prefix" size="10" maxlength="30" value="<?php echo htmlspecialchars($db_prefix, ENT_COMPAT, 'UTF-8'); ?>" />
</div>
<?php if ($bad_db_prefix): ?>
<p class="text-danger">Entrez de 2 à 30 caractères (lettre, chiffre ou souligné) en commençant par une lettre.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_site_admin_user or $missing_site_admin_password or $bad_site_admin_user or $weak_site_admin_password): ?> has-error<?php endif; ?>">
<label>Quels sont le nom et le mot de passe de l'administrateur du site&nbsp;?</label>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_site_admin_user" id="configure_site_admin_user" size="30" maxlength="40" value="<?php echo htmlspecialchars($site_admin_user, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'configure_site_admin_password')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
</div>
</div>
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_site_admin_password" id="configure_site_admin_password" size="30" maxlength="40" value="<?php echo htmlspecialchars($site_admin_password, ENT_COMPAT, 'UTF-8'); ?>" autocomplete="off" onkeypress="return focusonenter(event, 'configure_site_admin_user')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
</div>
</div>
</div>
<?php if ($missing_site_admin_user and $missing_site_admin_password): ?>
<p class="text-danger">Choisissez un identifiant pour l'administrateur du site et un mot de passe.</p>
<?php else: ?>
<?php if ($missing_site_admin_user or $bad_site_admin_user): ?>
<p class="text-danger">Entrez de 2 à 30 caractères (lettre, chiffre ou souligné) en commençant par une lettre.</p>
<?php endif; ?>
<?php if ($missing_site_admin_password): ?>
<p class="text-danger">Entrez un mot de passe.</p>
<?php elseif ($weak_site_admin_password): ?>
<p class="text-danger">Entrez une combinaison de lettres minuscules et majuscules et de chiffres d'au moins 6 caractères .</p>
<?php endif; ?>
<?php endif; ?>
</div>
<div class="form-group">
<button type="submit" class="btn <?php if ($bad_write_permission or $missing_sitename or $missing_webmaster or $missing_content_languages or $bad_default_language or $missing_db_admin_user or $missing_db_admin_password or $bad_db_type or $missing_db_name or $bad_db_name or $missing_db_host or $bad_db_host or $bad_db_prefix or $missing_db_user or $bad_db_user or $missing_db_password or $weak_db_password or $missing_site_admin_user or $bad_site_admin_user or $missing_site_admin_password or $weak_site_admin_password): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="configure_configure" id="configure_configure">Configurer</button>
</div>
</form>
