<?php

/**
 *
 * @copyright  2013-2014 (2016) izend.org
 * @version    5 (1)
 * @link       http://www.izend.org
 */
?>
<div id="linkbar" class="hidden-print">
<a href="https://www.facebook.com/" target="_blank" title="Rejoignez-nous sur Facebook"><span class="link-facebook">Facebook</span></a>
<a href="https://twitter.com/" target="_blank" title="Suivez-nous sur Twitter"><span class="link-twitter">Twitter</span></a>
<a href="http://www.buzzmii.com/" target="_blank" title="Visitez notre page sur BuZZmii"><span class="link-buzzmii">BuZZmii</span></a>
<a href="https://www.youtube.com/channel/" target="_blank" title="Visionnez nos vidéos sur YouTube"><span class="link-youtube">YouTube</span></a>
<a href="https://www.pinterest.com/" target="_blank" title="Regardez nos épingles sur Pinterest"><span class="link-pinterest">Pinterest</span></a>
<a href="<?php echo $base_path; ?>/fr/rss" title="Inscrivez-vous au flux RSS"><span class="link-rss">RSS</span></a>
<a href="<?php echo $base_path; ?>/fr/infolettre/abonnement" title="Recevez notre lettre d'information"><span class="link-newsletter">Infolettre</span></a>
</div>
