<?php

/**
 *
 * @copyright  2010-2026 (2016-2026) izend.org
 * @version    13 (3)
 * @link       http://www.izend.org
 */
?>
<?php $uri="$base_url/$request_path"; ?>
<a href="https://www.linkedin.com/sharing/share-offsite/?url=<?php echo rawurlencode($uri); ?>" target="_blank" rel="noopener noreferrer" title="Partager sur LinkedIn">
<?php switch ($sharemode): ?>
<?php case 'awesome': ?>
<i class="fab fa-linkedin-in"></i>
<?php break; ?>
<?php case 'lite': ?>
<?php default: ?>
<span class="social-linkedin">LinkedIn</span></a>
<?php break; ?>
<?php endswitch; ?>
</a>
