<?php

/**
 *
 * @copyright  2010-2016 (2016) izend.org
 * @version    10 (1)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form method="post">
<input type="hidden" name="login_token" value="<?php echo $token; ?>" />
<div class="form-group<?php if ($missing_login or $bad_login): ?> has-error<?php endif; ?>">
<label for="login_login"><?php if ($with_name): ?>Quel est votre nom de connexion&nbsp;?<?php else: ?>Quelle est votre adresse d'email&nbsp;?<?php endif; ?></label>
<div class="form-inline-auto">
<?php if ($facebook_login_url): ?>
<div class="input-group">
<?php endif; ?>
<input type="text" class="form-control" name="login_login" id="login_login" size="30" maxlength="100" placeholder="Identifiant" value="<?php echo htmlspecialchars($login, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'login_password')" />
<?php if ($with_facebook): ?>
<span class="input-group-addon social"><a href="<?php echo $facebook_login_url; ?>" title="Connectez-vous avec Facebook"><span class="social-facebook">Facebook</span></a></span>
</div>
<?php endif; ?>
</div>
<?php if ($with_name): ?>
<span class="help-block">Vous pouvez aussi entrer votre adresse d'email.</span>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_password or $access_denied): ?> has-error<?php endif; ?>">
<label for="login_password">Et votre clé d'accès&nbsp;?</label>
<div class="form-inline-auto">
<input type="password" class="form-control" name="login_password" id="login_password" size="20" maxlength="20" placeholder="Mot de passe" onkeypress="<?php if ($with_captcha): ?>return focusonenter(event, 'login_code')<?php else: ?>return submitonenter(event, 'login_enter')<?php endif; ?>" />
</div>
<?php if ($password_page): ?>
<span class="help-block">Si vous avez oublié votre mot de passe, <a href="<?php echo $password_page; ?>" rel="nofollow">cliquez ici</a>.</span>
<?php endif; ?>
</div>
<?php if ($with_captcha): ?>
<div class="form-group form-inline<?php if ($missing_code or $bad_code): ?> has-error<?php endif; ?>">
<div class="form-group form-inline-auto">
<img class="captcha" src="<?php echo $base_path; ?>/captcha/login" alt="" height="40" title="Code de vérification" />
<span class="form-control-static">:</span>
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="login_code" id="login_code" size="4" maxlength="4" title="4 lettres" value="" autocomplete="off" onkeypress="return submitonenter(event, 'login_enter')" />
</div>
</div>
<?php endif; ?>
<div class="form-group">
<button type="submit" class="btn <?php if ($internal_error or $missing_code or $bad_code or $missing_login or $bad_login or $missing_password): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="login_enter" id="login_enter">Entrer</button>
</div>
</form>
<?php if ($newuser_page): ?>
<p>Pour créer votre compte personnel, <a href="<?php echo $newuser_page; ?>" rel="nofollow">cliquez ici</a>.</p>
<?php endif; ?>
<?php if ($missing_code): ?>
<p class="text-danger">Entrez le code de vérification affiché dans l'image.</p>
<?php elseif ($bad_code): ?>
<p class="text-danger">Le code de vérification est incorrect.</p>
<?php endif; ?>
<?php if ($missing_login or $missing_password): ?>
<p class="text-danger">Entrez votre identifiant et votre mot de passe.</p>
<?php elseif ($bad_login): ?>
<p class="text-danger">L'identifiant est invalide.</p>
<?php elseif ($access_denied): ?>
<p class="text-danger">Accès refusé.</p>
<?php endif; ?>
<?php
$focus=false;
if ($missing_code or $bad_code) {
	$focus='#login_code';
}
else if ($missing_login or $bad_login) {
	$focus='#login_login';
}
else if ($missing_password or $access_denied) {
	$focus='#login_password';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
