<?php

/**
 *
 * @copyright  2010-2017 (2016-2017) izend.org
 * @version    21 (4)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php extract($infos); ?>
<form method="post">
<input type="hidden" name="register_token" value="<?php echo $token; ?>" />
<?php if ($with_timezone): ?>
<?php if ($timezone): ?>
<input type="hidden" name="register_timezone" value="<?php echo $timezone; ?>" />
<?php else: ?>
<input type="hidden" name="register_timezone" value="" />
<?php head('javascript', 'jstz'); ?>
<script type="text/javascript">
var tz = jstz.determine();
$('input[name=register_timezone]').val(tz.name());
</script>
<?php endif; ?>
<?php endif; ?>
<?php if ($with_info): ?>
<div class="form-group<?php if ($missing_firstname): ?> has-error<?php endif; ?>">
<label for="register_firstname">Quel est votre prénom&nbsp;?</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="register_firstname" id="register_firstname" size="30" maxlength="100" placeholder="Prénom" value="<?php echo htmlspecialchars($firstname, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'register_lastname')" />
</div>
</div>
<div class="form-group<?php if ($missing_lastname): ?> has-error<?php endif; ?>">
<label for="register_lastname">Et votre nom&nbsp;?</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="register_lastname" id="register_lastname" size="30" maxlength="100" placeholder="Nom" value="<?php echo htmlspecialchars($lastname, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, '<?php echo $with_name ? 'register_name' : 'register_mail'; ?>')" />
</div>
</div>
<?php endif; ?>
<?php if ($with_name): ?>
<div class="form-group<?php if ($missing_name or $bad_name or $duplicated_name): ?> has-error<?php endif; ?>">
<label for="register_name">Quel identifiant voulez-vous&nbsp;?</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="register_name" id="register_name" size="20" maxlength="20" placeholder="Identifiant" value="<?php echo htmlspecialchars($name, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'register_mail')" />
<?php if ($account_created): ?>
<img class="hidden-xxs" src="<?php echo $base_path; ?>/avatars/<?php echo $name; ?>.png" alt="" width="24" height="24" title="<?php echo $name; ?>" />
<?php endif; ?>
</div>
<span class="help-block">Choisissez un pseudo de 2 à 20 lettres.</span>
</div>
<?php endif; ?>
<div class="form-group<?php if ($missing_mail or $bad_mail or $duplicated_mail): ?> has-error<?php endif; ?>">
<label for="register_mail">Quelle est votre adresse d'email&nbsp;?</label>
<div class="form-inline-auto">
<?php if ($facebook_login_url): ?>
<div class="input-group">
<?php endif; ?>
<input type="text" class="form-control" name="register_mail" id="register_mail" size="30" maxlength="100" placeholder="nom@domaine.fr" value="<?php echo htmlspecialchars($mail, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, '<?php echo $with_website ? 'register_website' : ($with_password ? 'register_password' : 'register_code'); ?>')" />
<?php if ($with_facebook): ?>
<span class="input-group-addon social"><a href="<?php echo htmlspecialchars($facebook_login_url, ENT_COMPAT, 'UTF-8'); ?>" title="Connectez-vous avec Facebook"><span class="social-facebook">Facebook</span></a></span>
</div>
<?php endif; ?>
</div>
<span class="help-block">Votre mot de passe sera envoyé à cette adresse.</span>
</div>
<?php if ($with_website): ?>
<div class="form-group<?php if ($bad_website): ?> has-error<?php endif; ?>">
<label for="register_website">Avez-vous un site web&nbsp;?</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="register_website" id="register_website" size="30" maxlength="100" placeholder="www.domaine.fr" value="<?php echo htmlspecialchars($website, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, '<?php echo $with_password ? 'register_password' : 'register_code'; ?>')" />
</div>
</div>
<?php endif; ?>
<?php if ($with_password): ?>
<div class="form-group<?php if ($missing_password or $bad_password): ?> has-error<?php endif; ?>">
<label for="register_password">Choisissez un mot de passe&nbsp;:</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="register_password" id="register_password" size="20" maxlength="20" placeholder="Mot de passe" value="<?php echo htmlspecialchars($password, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'register_code')" />
</div>
<span class="help-block">Entrez au moins 6 caractères dont 1 chiffre.</span>
</div>
<?php endif; ?>
<?php if ($with_newsletter): ?>
<div class="checkbox">
<label><input type="checkbox" name="register_newsletter" id="register_newsletter" title="Infolettre"<?php if ($newsletter): ?> checked="checked"<?php endif; ?> />&nbsp;Je veux recevoir la lettre d'information par email</label>
</div>
<?php endif; ?>
<?php if ($with_confirmation): ?>
<div class="checkbox<?php if ($missing_confirmation): ?> has-error<?php endif; ?>">
<label><input type="checkbox" name="register_confirmed" id="register_confirmed" title="Confirmation"<?php if ($confirmed): ?> checked="checked"<?php endif; ?> />&nbsp;Je souhaite créer un compte</label>
</div>
<?php endif; ?>
<?php if ($with_captcha): ?>
<div class="form-group form-inline<?php if ($missing_code or $bad_code): ?> has-error<?php endif; ?>">
<div class="form-group form-inline-auto">
<img class="captcha" src="<?php echo $base_path; ?>/captcha/register" alt="" height="40" title="Code de vérification" />
<span class="form-control-static">:</span>
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="register_code" id="register_code" size="4" maxlength="4" title="4 lettres" value="" autocomplete="off" onkeypress="return submitonenter(event, 'register_register')" />
</div>
</div>
<?php endif; ?>
<div class="form-group">
<button type="submit" class="btn <?php if ($internal_error or $missing_code or $bad_code or $missing_name or $bad_name or $duplicated_name or $missing_mail or $bad_mail or $duplicated_mail or $bad_website or $missing_password or $bad_password or $missing_lastname or $missing_firstname or $missing_confirmation): ?>btn-danger<?php elseif ($account_created): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="register_register" id="register_register">Envoyer</button>
</div>
</form>
<?php if ($missing_code): ?>
<p class="text-danger">Entrez le code de vérification affiché dans l'image.</p>
<?php elseif ($bad_code): ?>
<p class="text-danger">Le code de vérification est incorrect.</p>
<?php endif; ?>
<?php if ($duplicated_name): ?>
<p class="text-danger">Cet identifiant est déjà pris.</p>
<?php endif; ?>
<?php if ($duplicated_mail): ?>
<p class="text-danger">Cette adresse d'email est déjà utilisée.</p>
<?php endif; ?>
<?php if ($missing_confirmation): ?>
<p class="text-danger">Cochez la case de confirmation.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>" rel="nofollow">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($account_created): ?>
<p>Votre compte a été créé. Le mot de passe a été envoyé par email à votre adresse.
Pour vous identifier, <a href="<?php echo $user_page; ?>">cliquez ici</a>.</p>
<?php endif; ?>
<?php
$focus=false;
if ($missing_code or $bad_code) {
	$focus='#register_code';
}
else if ($missing_firstname) {
	$focus='#register_firstname';
}
else if ($missing_lastname) {
	$focus='#register_lastname';
}
else if ($missing_name or $bad_name or $duplicated_name) {
	$focus='#register_name';
}
else if ($missing_mail or $bad_mail or $duplicated_mail) {
	$focus='#register_mail';
}
else if ($bad_website) {
	$focus='#register_website';
}
else if ($missing_password or $bad_password) {
	$focus='#register_password';
}
else if ($missing_confirmation) {
	$focus='#register_code';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
