<?php

/**
 *
 * @copyright  2010-2016 (2016) izend.org
 * @version    11 (1)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php extract($infos); ?>
<form method="post">
<input type="hidden" name="remindme_token" value="<?php echo $token; ?>" />
<div class="form-group<?php if ($missing_login or $bad_login): ?> has-error<?php endif; ?>">
<label for="remindme_login"><?php if ($with_name): ?>Quel est votre nom de connexion&nbsp;?<?php else: ?>Quelle est votre adresse d'email&nbsp;?<?php endif; ?></label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="remindme_login" id="remindme_login" size="40" maxlength="100" placeholder="Identifiant" value="<?php echo htmlspecialchars($login, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'remindme_code')" />
</div>
<?php if ($with_name): ?>
<span class="help-block">Vous pouvez aussi entrer votre adresse d'email.</span>
<?php endif; ?>
</div>
<div class="checkbox<?php if ($missing_confirmation): ?> has-error<?php endif; ?>">
<label><input type="checkbox" name="remindme_confirmed" id="remindme_confirmed" title="Confirmation"<?php if ($confirmed): ?> checked="checked"<?php endif; ?> />&nbsp;Je veux recevoir un nouveau mot de passe</label>
</div>
<?php if ($with_captcha): ?>
<div class="form-group form-inline<?php if ($missing_code or $bad_code): ?> has-error<?php endif; ?>">
<div class="form-group form-inline-auto">
<img class="captcha" src="<?php echo $base_path; ?>/captcha/remindme" alt="" height="40" title="Code de vérification" />
<span class="form-control-static">:</span>
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="remindme_code" id="remindme_code" size="4" maxlength="4" title="4 lettres" value="" autocomplete="off" onkeypress="return submitonenter(event, 'remindme_send')" />
</div>
</div>
<?php endif; ?>
<div class="form-group">
<button type="submit" class="btn <?php if ($internal_error or $missing_code or $bad_code or $missing_login or $bad_login or $missing_confirmation): ?>btn-danger<?php elseif ($email_sent): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="remindme_send" id="remindme_send">Envoyer</button>
</div>
</form>
<?php if ($missing_code): ?>
<p class="text-danger">Entrez le code de vérification affiché dans l'image.</p>
<?php elseif ($bad_code): ?>
<p class="text-danger">Le code de vérification est incorrect.</p>
<?php endif; ?>
<?php if ($missing_confirmation): ?>
<p class="text-danger">Cochez la case de confirmation.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>" rel="nofollow">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($email_sent): ?>
<p>Un nouveau mot de passe vous a été envoyé par email.
Pour vous identifier, <a href="<?php echo $user_page; ?>">cliquez ici</a>.</p>
<?php endif; ?>
<?php
$focus=false;
if ($missing_code or $bad_code) {
	$focus='#remindme_code';
}
else if ($missing_login or $bad_login) {
	$focus='#remindme_login';
}
else if ($missing_confirmation) {
	$focus='#remindme_code';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
