<?php

/**
 *
 * @copyright  2010-2022 (2016-2022) izend.org
 * @version    7 (2)
 * @link       http://www.izend.org
 */
?>
<?php if (!empty($search_url)): ?>
<form method="post" action="<?php echo $search_url; ?>" id="searchinput" role="search">
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="searchtext" id="searchtext" size="20" maxlength="100" value="<?php if ($search_text): ?><?php echo htmlspecialchars($search_text, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" placeholder="Recherche" />
<span class="input-group-btn">
<button type="submit" class="btn btn-default" name="search" id="search"><span class="glyphicon glyphicon-search"></span></button>
</span>
</div>
</div>
</form>
<?php if (!empty($suggest_url)): ?>
<?php head('javascript', 'jquery-ui'); ?>
<?php if (true): ?>
<?php head('stylesheet', 'jquery-ui', 'screen'); ?>
<?php endif; ?>
<script>
//<![CDATA[
$('input#searchtext')
.bind('keydown', function(event) {
    if (event.keyCode === $.ui.keyCode.TAB && $(this).data('autocomplete').menu.active) {
        event.preventDefault();
    }
})
.autocomplete({
    appendTo: '#searchinput',
    minLength: 3,
    source: function(request, response) {
        var pos = getcaretposition(this.element.get(0));
        var term = getwordat(request.term, pos);

        if (!term || term.length < this.options.minLength) {
            this.close();
        }
        else {
            $.getJSON('<?php echo $suggest_url; ?>', {term: term}, response);
        }
    },
    select: function(event, ui) {
        var pos = getcaretposition(this);
		var s = this.value;

        for (var i = pos-1; i >= 0 && s[i] != ' '; i--)
            ;
        var beg = i < 0 ? 0 : i+1;

        for (var i = pos; i < s.length && s[i] != ' '; i++)
             ;
        var end = i >= s.length ? s.length : i;

        this.value = s.substring(0, beg) + ui.item.value + s.substring(end);

        setcaretposition(this, beg + ui.item.value.length);

        return false;
    },
    focus: function() {
        return false;
    }
});
//]]>
</script>
<?php endif; ?>
<?php endif; ?>
