<?php

/**
 *
 * @copyright  2012-2023 (2016-2023) izend.org
 * @version    16 (4)
 * @link       http://www.izend.org
 */
?>
<div id="socialbar" class="hidden-print">
<a href="https://www.facebook.com/pages/" title="Rejoignez-nous sur Facebook"><span class="social-facebook">Facebook</span></a>
<?php if (false): ?>
<a href="https://twitter.com/#!/" title="Suivez-nous sur Twitter"><span class="social-twitter">Twitter</span ></a>
<?php endif; ?>
<a href="https://twitter.com/#!/" title="Suivez-nous sur X"><span class="social-x-twitter">X</span ></a>
<a href="http://fr.linkedin.com/" title="Connectez-vous à notre réseau sur LinkedIn"><span class="social-linkedin">LinkedIn</span></a>
<a href="https://www.youtube.com/channel/" title="Visionnez nos vidéos sur YouTube"><span class="social-youtube">YouTube</span></a>
<a href="https://www.pinterest.com/" title="Regardez nos épingles sur Pinterest"><span class="social-pinterest">Pinterest</span></a>
<a href="<?php echo $base_path; ?>/fr/rss" rel="nofollow" title="Inscrivez-vous au flux RSS"><span class="social-rss">RSS</span></a>
<a href="<?php echo $base_path; ?>/fr/infolettre/abonnement" rel="nofollow" title="Recevez notre lettre d'information"><span class="social-newsletter">Infolettre</span></a>
<a href="<?php echo $base_path; ?>/fr/contact" rel="nofollow" title="Contactez-nous"><span class="social-email">Email</span></a>
</div>
