<?php

/**
 *
 * @copyright  2012-2015 (2016) izend.org
 * @version    11 (1)
 * @link       http://www.izend.org
 */
?>
<div id="socialbar" class="hidden-print">
<a href="https://www.facebook.com/pages/" target="_blank" title="Rejoignez-nous sur Facebook"><span class="social-facebook">Facebook</span></a>
<a href="https://twitter.com/#!/" target="_blank" title="Suivez-nous sur Twitter"><span class="social-twitter">Twitter</span ></a>
<a href="https://plus.google.com/" target="_blank" title="Restez en contact avec Google+"><span class="social-gplus">Google+</span></a>
<a href="http://fr.linkedin.com/" target="_blank" title="Connectez-vous à notre réseau sur LinkedIn"><span class="social-linkedin">LinkedIn</span></a>
<a href="https://www.youtube.com/channel/" target="_blank" title="Visionnez nos vidéos sur YouTube"><span class="social-youtube">YouTube</span></a>
<a href="https://www.pinterest.com/" target="_blank" title="Regardez nos épingles sur Pinterest"><span class="social-pinterest">Pinterest</span></a>
<a href="<?php echo $base_path; ?>/fr/rss" target="_blank" rel="nofollow" title="Inscrivez-vous au flux RSS"><span class="social-rss">RSS</span></a>
<a href="<?php echo $base_path; ?>/fr/infolettre/abonnement" rel="nofollow" title="Recevez notre lettre d'information"><span class="social-newsletter">Infolettre</span></a>
</div>
