<?php

/**
 *
 * @copyright  2015-2026 izend.org
 * @version    6
 * @link       http://www.izend.org
 */
?>
<div id="twitter-timeline"><a class="twitter-timeline" href="https://x.com/<?php echo $link_tweetline; ?>" lang="fr" data-width="480" data-height="480" data-link-color="#eb4823"<?php if (!empty($tweetline_limit)): ?> data-tweet-limit="<?php echo $tweetline_limit; ?>"<?php endif; ?> data-chrome="noborders nofooter noscrollbar transparent">Tweets de @<?php echo $link_tweetline; ?></a></div>
<script async src="https://platform.x.com/widgets.js" charset="utf-8"></script>
