<?php

/**
 *
 * @copyright  2012-2017 (2016) izend.org
 * @version    12 (1)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php extract($infos); ?>
<form method="post" enctype="multipart/form-data">
<input type="hidden" name="upload_token" value="<?php echo $token; ?>" />
<?php if (!empty($maxfilesize)): ?>
<input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $maxfilesize; ?>" />
<?php endif; ?>
<div class="form-group">
<input type="file" name="upload_file" id="upload_file" title="" />
</div>
<div class="form-group">
<button type="submit" class="btn <?php if ($missing_file or $bad_file or $bad_name or $bad_size or $bad_copy or $copy_error): ?>btn-danger<?php elseif ($file_copied): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="upload_put" id="upload_put">Télécharger</button>
</div>
</form>
<script type="text/javascript">
var file=$('#upload_file');
var upload=$('#upload_put');

file.css({ position: 'absolute', left: '-9999px' });

upload.on('click', function(e) { e.preventDefault(); file.click(); });

file.change(function() {
    if (file.val()) {
        upload.off('click').click();
    }
});
</script>
