<?php

/**
 *
 * @copyright  2011-2019 (2017-2022) izend.org
 * @version    27 (6)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php extract($infos); ?>
<form method="post">
<input type="hidden" name="useredit_token" value="<?php echo $token; ?>" />
<?php if ($user_accessed): ?>
<input type="hidden" name="useredit_accessed" value="<?php echo $user_accessed; ?>" />
<?php endif; ?>
<?php if ($with_info): ?>
<div class="form-group<?php if ($missing_firstname): ?> has-error<?php endif; ?>">
<label for="useredit_firstname">Prénom</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_firstname" id="useredit_firstname" size="30" maxlength="100" placeholder="Prénom" value="<?php echo htmlspecialchars($user_firstname, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'useredit_lastname')" />
</div>
</div>
<div class="form-group<?php if ($missing_lastname): ?> has-error<?php endif; ?>">
<label for="useredit_lastname">Nom</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_lastname" id="useredit_lastname" size="30" maxlength="100" placeholder="Nom" value="<?php echo htmlspecialchars($user_lastname, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, '<?php echo $with_name ? 'useredit_name' : 'useredit_mail'; ?>')" />
</div>
</div>
<?php endif; ?>
<?php if ($with_name): ?>
<div class="form-group<?php if ($missing_name or $bad_name or $duplicated_name): ?> has-error<?php endif; ?>">
<label for="useredit_name">Identifiant</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_name" id="useredit_name" size="20" maxlength="20" placeholder="2 à 20 lettres" value="<?php echo htmlspecialchars($user_name, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'useredit_mail')" />
<img class="hidden-xxs" src="<?php echo $base_path; ?>/avatars/<?php echo $user_name; ?>.png" alt="" width="24" height="24" title="<?php echo $user_name; ?>" />
</div>
</div>
<?php else: ?>
<input type="hidden" name="useredit_name" value="<?php echo htmlspecialchars($user_name, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<div class="form-group<?php if ($missing_mail or $bad_mail or $duplicated_mail): ?> has-error<?php endif; ?>">
<label for="useredit_mail">Email</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_mail" id="useredit_mail" size="30" maxlength="100" placeholder="nom@domaine.fr" value="<?php echo htmlspecialchars($user_mail, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'useredit_modify')" />
</div>
</div>
<?php if ($with_role): ?>
<div class="form-group">
<?php $rolename=array('administrator' => 'administrateur', 'writer' => 'rédacteur', 'reader' => 'lecteur', 'moderator' => 'modérateur'); ?>
<?php foreach ($supported_roles as $role): ?><label class="checkbox-inline"><input type="checkbox" name="useredit_role[]" value="<?php echo $role; ?>"<?php if ($user_role and in_array($role, $user_role)):?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;<?php echo $rolename[$role]; ?></span></label><?php echo PHP_EOL; ?><?php endforeach; ?>
</div>
<?php endif; ?>
<?php if ($with_website): ?>
<div class="form-group<?php if ($bad_website): ?> has-error<?php endif; ?>">
<label for="useredit_website">Site web</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_website" id="useredit_website" size="30" maxlength="100" placeholder="www.domaine.fr" value="<?php echo htmlspecialchars($user_website, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'useredit_modify')" />
</div>
</div>
<?php else: ?>
<input type="hidden" name="useredit_website" value="<?php echo htmlspecialchars($user_website, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<?php if ($with_timezone): ?>
<div class="form-group<?php if ($bad_timezone): ?> has-error<?php endif; ?>">
<label for="useredit_timezone">Fuseau horaire</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_timezone" id="useredit_timezone" size="30" maxlength="100" placeholder="Europe/Paris" value="<?php echo htmlspecialchars($user_timezone, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'useredit_modify')" />
</div>
</div>
<?php else: ?>
<input type="hidden" name="useredit_timezone" value="<?php echo htmlspecialchars($user_timezone, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<?php if ($with_locale): ?>
<div class="form-group">
<?php foreach ($system_languages as $lang): ?><label class="radio-inline"><input type="radio" name="useredit_locale" value="<?php echo $lang; ?>" title="<?php echo $lang; ?>"<?php if ($lang == $user_locale): ?> checked="checked"<?php endif; ?> />&nbsp;<span class="lang-<?php echo $lang; ?>" title="<?php echo $lang; ?>"><?php echo $lang; ?></span></label><?php echo PHP_EOL; ?><?php endforeach; ?>
</div>
<?php else: ?>
<input type="hidden" name="useredit_locale" value="<?php echo htmlspecialchars($user_locale, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<?php if ($with_status): ?>
<div class="form-group">
<fieldset id="useredit_status">
<legend>Statut</legend>
<label class="checkbox-inline">
<input type="checkbox" name="useredit_active"<?php if ($user_active): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;actif</span>
</label>
<label class="checkbox-inline">
<input type="checkbox" name="useredit_banned"<?php if ($user_banned): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;banni</span>
</label>
<label class="checkbox-inline">
<input type="checkbox" name="useredit_confirmed"<?php if ($user_confirmed): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;confirmé</span>
</label>
</fieldset>
</div>
<?php if ($user_accessed): ?>
<?php require_once 'datefr.php'; ?>
<p><small>Dernier accès le <?php echo longdate_fr($user_accessed); ?> à <?php echo date('H:i', $user_accessed); ?></small></p>
<?php endif; ?>
<?php endif; ?>
<div class="form-group">
<?php if ($with_delete): ?>
<?php if ($confirm_delete): ?>
<button type="submit" class="btn btn-warning" name="useredit_confirmdelete" id="useredit_confirmdelete">Confirmer</button>
<span class="form-control-static">la suppression ou</span>
<button type="submit" class="btn btn-default" name="useredit_cancel" id="useredit_cancel">Annuler</button>
<?php else: ?>
<button type="submit" class="btn <?php if ($internal_error or $missing_name or $bad_name or $duplicated_name or $missing_mail or $bad_mail or $duplicated_mail or $bad_role or $bad_website or $bad_timezone or $missing_locale or $bad_locale or $missing_lastname or $missing_firstname): ?>btn-danger<?php elseif ($account_modified): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="useredit_modify" id="useredit_modify">Modifier</button>
<span class="form-control-static">le profil ou</span>
<button type="submit" class="btn btn-default" name="useredit_delete" id="useredit_delete">Supprimer</button>
<span class="form-control-static">le compte</span>
<?php endif; ?>
<?php else: ?>
<button type="submit" class="btn <?php if ($internal_error or $missing_name or $bad_name or $duplicated_name or $missing_mail or $bad_mail or $duplicated_mail or $bad_role or $bad_website or $bad_timezone or $missing_locale or $bad_locale or $missing_lastname or $missing_firstname): ?>btn-danger<?php elseif ($account_modified): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="useredit_modify" id="useredit_modify">Modifier</button>
<?php endif; ?>
</div>
<?php if ($with_newpassword): ?>
<div class="form-group<?php if ($missing_newpassword or $bad_newpassword or $missing_oldpassword or $bad_oldpassword): ?> has-error<?php endif; ?>">
<?php if ($with_oldpassword): ?>
<label for="useredit_oldpassword">Mot de passe actuel</label>
<div class="form-inline-auto">
<input type="password" class="form-control" name="useredit_oldpassword" id="useredit_oldpassword" size="20" maxlength="20" placeholder="6 lettres et chiffres" title="au moins 6 lettres et chiffres" onkeypress="return focusonenter(event, 'useredit_newpassword')" /><?php if ($with_viewpassword): ?>&nbsp;<span class="glyphicon glyphicon-eye-open cursor-pointer" aria-hidden="true"></span><?php endif; ?>
</div>
<?php endif; ?>
<label for="useredit_newpassword">Nouveau mot de passe</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_newpassword" id="useredit_newpassword" size="20" maxlength="20" placeholder="6 lettres et chiffres" title="au moins 6 lettres et chiffres" value="<?php echo htmlspecialchars($user_newpassword, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'useredit_change')" />
</div>
</div>
<div class="form-group">
<button type="submit" class="btn <?php if ($internal_error or $missing_newpassword or $bad_newpassword): ?>btn-danger<?php elseif ($password_changed): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="useredit_change" id="useredit_change">Changer</button>
</div>
<?php endif; ?>
</form>
<?php if ($with_newpassword and $with_oldpassword and $with_viewpassword): ?>
<script>
(function() {
	const password = document.getElementById('useredit_oldpassword');
	password.nextElementSibling.addEventListener('click', () => password.type = password.type == 'password' ? 'text' : 'password');
})();
</script>
<?php endif; ?>
<?php if ($missing_lastname and $missing_firstname): ?>
<p class="text-danger">Un nom et un prénom sont obligatoires.</p>
<?php else: ?>
<?php if ($missing_lastname): ?>
<p class="text-danger">Un nom est obligatoire.</p>
<?php endif; ?>
<?php if ($missing_firstname): ?>
<p class="text-danger">Un prénom est obligatoire.</p>
<?php endif; ?>
<?php endif; ?>
<?php if ($missing_name): ?>
<p class="text-danger">Un identifiant est obligatoire.</p>
<?php elseif ($bad_name): ?>
<p class="text-danger">Un identifiant doit comporter de 2 à 20 lettres.</p>
<?php elseif ($duplicated_name): ?>
<p class="text-danger">Cet identifiant est déjà pris.</p>
<?php endif; ?>
<?php if ($missing_mail): ?>
<p class="text-danger">Une adresse d'email est obligatoire.</p>
<?php elseif ($bad_mail): ?>
<p class="text-danger">L'adresse d'email est invalide.</p>
<?php elseif ($duplicated_mail): ?>
<p class="text-danger">Cette adresse d'email est déjà utilisée.</p>
<?php endif; ?>
<?php if ($bad_timezone): ?>
<p class="text-danger">Le fuseau horaire est incorrect.</p>
<?php endif; ?>
<?php if ($bad_website): ?>
<p class="text-danger">L'URL du site web est invalide.</p>
<?php endif; ?>
<?php if ($missing_newpassword or $bad_newpassword or $missing_oldpassword or $bad_oldpassword): ?>
<p class="text-danger">Entrez une combinaison de lettres et de chiffres d'au moins 6 caractères.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>Une erreur interne s'est produite.
<?php if ($contact_page): ?>Si vous pouvez décrire le problème, merci de <a href="<?php echo $contact_page; ?>" rel="nofollow">nous contacter</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($account_modified): ?>
<p>Les données du compte ont été modifiées.</p>
<?php endif; ?>
<?php if ($password_changed): ?>
<p>Le mot de passe a été changé.</p>
<?php endif; ?>
<?php
$focus=false;
if ($missing_firstname) {
	$focus='#useredit_firstname';
}
else if ($missing_lastname) {
	$focus='#useredit_lastname';
}
else if ($missing_name or $bad_name or $duplicated_name) {
	$focus='#useredit_name';
}
else if ($missing_mail or $bad_mail or $duplicated_mail) {
	$focus='#useredit_mail';
}
else if ($bad_timezone) {
	$focus='#useredit_timezone';
}
else if ($bad_website) {
	$focus='#useredit_website';
}
else if ($missing_oldpassword or $bad_oldpassword) {
	$focus='#useredit_oldpassword';
}
else if ($missing_newpassword or $bad_newpassword) {
	$focus=$with_oldpassword ? '#useredit_oldpassword' : '#useredit_newpassword';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
