<?php

/**
 *
 * @copyright  2013-2017 (2016) izend.org
 * @version    11 (2)
 * @link       http://www.izend.org
 */
?>
<form method="post">
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="usersearch_what" id="usersearch_what" size="20" maxlength="100" placeholder="Identifiant" value="<?php echo htmlspecialchars($what, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'usersearch_search')" />
</div>
<div class="form-group">
<button type="submit" class="btn btn-default" name="usersearch_search" id="usersearch_search">Chercher</button>
</div>
</div>
</form>
<?php if ($count): $i=1; ?>
<p><strong><span class="lead"><?php $s=$count > 1 ? 's' : ''; echo $count; ?></span> utilisateur<?php echo $s; ?></strong></p>
<?php if ($count > $pagesize): ?>
<?php
require_once 'pagerange.php';

$npages=ceil($count / $pagesize);
$pagenums=page_range($page, $npages, 2);
?>
<ul class="pagination">
<?php if ($pagenums[0] < $page): ?>
<li><a href="?q=<?php echo urlencode($what); ?>&amp;p=<?php echo $page-1; ?>">&laquo;</a></li>
<?php endif; ?>
<?php foreach ($pagenums as $p): ?>
<li<?php if ($p == $page): ?> class="active"<?php endif; ?>>
<a href="?q=<?php echo urlencode($what); ?>&amp;p=<?php echo $p; ?>"><?php echo $p; ?></a>
</li>
<?php endforeach; ?>
<?php if ($pagenums[count($pagenums) - 1] > $page): ?>
<li><a href="?q=<?php echo urlencode($what); ?>&amp;p=<?php echo $page+1; ?>">&raquo;</a></li>
<?php endif; ?>
</ul>
<?php endif; ?>
<div class="table-responsive">
<table class="table table-striped table-hover">
<tbody>
<?php foreach ($result as $r): extract($r);?>
<tr>
<?php if ($with_name): ?>
<td><?php if ($user_name): ?><?php if ($edit): ?><a href="<?php echo $edit; ?>"><?php endif; ?><?php echo $user_name; ?><?php if ($edit): ?></a><?php endif; ?><?php else: ?>&nbsp;<?php endif; ?></td>
<td><?php if ($user_name): ?><img class="avatar" src="<?php echo $base_path; ?>/avatars/<?php echo $user_name; ?>.png" alt="" width="24" height="24" /><?php else: ?>&nbsp;<?php endif; ?></td>
<?php endif; ?>
<td><?php if ($user_mail): ?><?php if ($edit and (!$with_name or !$user_name)): ?><a href="<?php echo $edit; ?>"><?php endif; ?><?php echo $user_mail; ?><?php if ($edit and (!$with_name or !$user_name)): ?></a><?php endif; ?><?php else: ?>&nbsp;<?php endif; ?></td>
<td class="text-right"><?php if ($user_logged): ?><?php echo $user_logged; ?><?php else: ?>&nbsp;<?php endif; ?></td>
<td><?php if ($user_accessed): ?><?php echo date('d/m/Y H:i', $user_accessed); ?><?php else: ?>&nbsp;<?php endif; ?></td>
<td><?php if (!$user_active or $user_banned): ?><span class="glyphicon glyphicon-exclamation-sign text-danger"></span><?php else: ?>&nbsp;<?php endif; ?></td>
<?php if ($with_website): ?>
<td><?php if ($user_website): ?><a href="http://<?php echo $user_website; ?>"><?php echo $user_website; ?></a><?php else: ?>&nbsp;<?php endif; ?></td>
<?php endif; ?>
</tr>
<?php $i++; ?>
<?php endforeach; ?>
</tbody>
</table>
</div>
<?php else: ?>
<?php if (!empty($what)): ?>
<p><strong><span class="lead">0</span> utilisateur</strong></p>
<?php endif; ?>
<?php endif; ?>
