<?php

/**
 *
 * @copyright  2014-2018 (2016) izend.org
 * @version    5 (1)
 * @link       http://www.izend.org
 */
?>
<?php if ($visits > 0): ?>
<?php require_once 'countformat.php'; ?>
<div class="visits" title="<?php echo number_format($visits, 0, ',', ' '); ?> visite<?php if ($visits > 1): ?>s<?php endif; ?>">
<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
<span class="count"><?php echo count_format($visits, ',', ' '); ?></span>
</div>
<?php endif; ?>
<?php if ($visit_page): ?>
<script>
$(document).ready(function() {$.get('<?php echo $visit_page; ?>');});
</script>
<?php endif; ?>
