<?php

/**
 *
 * @copyright  2012 (2016) izend.org
 * @version    4 (1)
 * @link       http://www.izend.org
 */
?>
<?php if ($vote_total > 0 or !$nomore): ?>
<?php if (!$nomore): ?>
<form class="vote" method="post">
<?php else: ?>
<div class="vote">
<?php endif; ?>
<?php if ($vote_total > 0): ?>
<?php require_once 'countformat.php'; ?>
<span class="count" title="<?php echo number_format($vote_total, 0, ',', ' '); ?> recommandation<?php if ($vote_total > 1): ?>s<?php endif; ?>"><?php echo count_format($vote_total, ',', ' '); ?></span>
<?php endif; ?>
<?php if (!$nomore): ?>
<input type="hidden" name="vote_id" value="<?php echo $content_id; ?>" />
<input type="hidden" name="vote_type" value="<?php echo $content_type; ?>" />
<button type="submit" class="btn btn-blank" name="vote_plusone" title="Recommander"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></button>
<?php endif; ?>
<?php if (!$nomore): ?>
</form>
<?php else: ?>
</div>
<?php endif; ?>
<?php endif; ?>
