<?php

/**
 *
 * @copyright  2019 (2019) izend.org
 * @version    2 (1)
 * @link       http://www.izend.org
 */
?>
<?php switch ($mode): ?>
<?php case 'lite': ?>
<a href="whatsapp://send?text=<?php echo rawurlencode("$base_url/$request_path"); ?>" title="Partager sur WhatsApp"><span class="social-whatsapp">WhatsApp</span></a>
<?php break; ?>
<?php case 'awesome': ?>
<a href="whatsapp://send?text=<?php echo rawurlencode("$base_url/$request_path"); ?>" title="Partager sur WhatsApp"><i class="fab fa-whatsapp"></i></a>
<?php break; ?>
<?php default: ?>
<?php break; ?>
<?php endswitch; ?>
