<?php

/**
 *
 * @copyright  2010-2014 (2016) izend.org
 * @version    4 (1)
 * @link       http://www.izend.org
 */
?>
<h3>Management</h3>
<div class="pull-right">
<?php if (!empty($newsletter_page)): ?>
<a class="btn bn-link center-block" href="<?php echo $newsletter_page; ?>" rel="nofollow"><img src="/images/theme/envelopelarge.png" alt="" title="Newsletter" /></a>
<?php endif; ?>
<?php if (!empty($balance)): ?>
<?php echo $balance; ?>
<?php endif; ?>
<?php if (!empty($upload)): ?>
</div>
<h4>Content</h4>
<?php echo $upload; ?>
<?php endif; ?>
<h4>Community</h4>
<?php if (!empty($newuser_page)): ?>
<p>To create an account, <a href="<?php echo $newuser_page; ?>" rel="nofollow">click here</a>.</p>
<?php endif; ?>
<?php echo $usersearch; ?>
