<?php

/**
 *
 * @copyright  2012-2014 (2016) izend.org
 * @version    2 (1)
 * @link       http://www.izend.org
 */
?>
<?php head('stylesheet', 'paypal.css', 'screen'); ?>
<form method="post">
<button type="submit" class="btn btn-link" name="balance_balance" id="balance_balance" title="Balance"><i class="paypal-logo"></i></button>
</form>
<?php if ($balance): ?>
<span class="lead center-block text-center"><?php echo number_format($balance, 2, '.', ' '); ?>&nbsp;<?php echo $currency; ?></span>
<?php endif; ?>
