<?php

/**
 *
 * @copyright  2010-2011 (2016) izend.org
 * @version    6 (1)
 * @link       http://www.izend.org
 */
?>
<?php if (!empty($contact_page) or !empty($user_page) or !empty($nobody_page) or !empty($account_page) or !empty($edit_page) or !empty($view_page) or !empty($validate_page) or !empty($admin_page)): ?>
<ul id="navbar-controls" class="nav navbar-nav">
<?php if (!empty($nobody_page)): ?>
<li><a href="<?php echo $nobody_page; ?>" rel="nofollow" title="Quit"><span class="glyphicon glyphicon-off" aria-hidden="true"></span></a></li>
<?php endif; ?>
<?php if (!empty($contact_page)): ?>
<li><a href="<?php echo $contact_page; ?>" rel="nofollow" title="Contact us"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></a></li>
<?php endif; ?>
<?php if (!empty($user_page)): ?>
<li><a href="<?php echo $user_page; ?>" rel="nofollow" title="Your account"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a></li>
<?php endif; ?>
<?php if (!empty($account_page)): ?>
<li><a href="<?php echo $account_page; ?>" rel="nofollow" title="Your account"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a></li>
<?php endif; ?>
<?php if (!empty($edit_page)): ?>
<li><a href="<?php echo $edit_page; ?>" title="Edit" rel="nofollow"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></li>
<?php elseif ($view_page): ?>
<li><a href="<?php echo $view_page; ?>" title="View" rel="nofollow"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span></a></li>
<?php endif; ?>
<?php if (!empty($validate_page)): ?>
<li><a href="http://validator.w3.org/check?uri=<?php echo $base_root . $validate_page; ?>" target="validator.w3.org" rel="nofollow" title="Validate"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></li>
<?php endif; ?>
<?php if (!empty($admin_page)): ?>
<li><a href="<?php echo $admin_page; ?>" rel="nofollow" title="Manage"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a></li>
<?php endif; ?>
</ul>
<?php endif; ?>
