<?php

/**
 *
 * @copyright  2010-2017 (2016) izend.org
 * @version    14 (2)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<p>Your <b>iZend</b> site is practically operational.
Read the following instructions, fill in the form and press Configure to run the configurator.</p>
<h6>Parameters</h6>
<p>Enter the name of the site, the email address of the webmaster and select the languages managed by the site.
Initially, you will only be allowed to choose among the languages supported by the core of the software.
Once the site is configured, you will be able to easily add contents in several other languages.
All the parameters of the software are in the folder <i>includes</i>.
The configurator rewrites the configuration files <i>config.inc</i>, <i>db.inc</i> and <i>aliases.inc</i> and the files <i>sitemap.xml</i>, <i>robots.txt</i> and <i>.htaccess</i> in the root directory of the site.</p>
<p>For more security, check that the access to the configuration files is limited to the server:</p>
<pre><code>$ cd <?php echo ROOT_DIR; ?>; sudo chgrp -R www-data .; chmod -R g+w .
$ cd <?php echo ROOT_DIR; ?>/includes; chmod 660 db.inc config.inc settings.inc aliases.inc paypal.inc</code></pre>
<p>NOTE: The name of the execution group of the server is defined by the Group directive, generally in the file <i>/etc/apache2/apache2.conf</i>.</p>
<h6>Logo</h6>
<p>The configurator generates a logo based on the name of the site and saves it in the file <i>sitelogo.png</i> in the folder <i>logos</i>.
You will probably want to change it.</p>
<h6>Database</h6>
<p>iZend can function without a database.
In this mode, you will still be able to benefit from the architecture of the software, but you will have to write the pages of the site without the editor.
Choose this configuration to put on-line a site with limited resources.
Note that iZend can occupy very little space on disk.</p>
<p>To exploit the full potential of iZend, you need a database server.
You can use either MySQL or PostgreSQL.
The configurator can create a new database or use an already existing database.
<b>IMPORTANT</b>: If the database is shared, ask the configurator to add a prefix to the table names.
In any case, using a prefix is safer.</p>
<p>NOTE: If you develop the site locally before it is put on-line, which is recommended, use the same parameters on both servers.</p>
<h5>Configuration</h5>
<?php if ($bad_write_permission): ?>
<div class="alert alert-danger" role="alert">
<p>The server isn't allowed to modify <?php if (count($bad_write_permission) > 1): ?>the following folders or files<?php else: ?>the following folder or file<?php endif; ?> in the folder <i><?php echo ROOT_DIR; ?></i>:
</p>
<ul class="list-unstyled">
<?php foreach ($bad_write_permission as $file): ?>
<li><i><?php echo $file; ?></i></li>
<?php endforeach; ?>
</ul>
</div>
<p>To modify the access rights, try the following command:</p>
<pre><code>$ cd <?php echo ROOT_DIR; ?>; chmod a+w<?php foreach ($bad_write_permission as $fname) { echo ' ', $fname; }; ?></code></pre>
<?php endif; ?>
<?php $nerrors=count(array_keys($errors, true, true)); ?>
<?php if ($nerrors > 0): ?>
<div class="alert alert-danger" role="alert">
<p>The form has <?php echo $nerrors; ?> error<?php if ($nerrors > 1): ?>s<?php endif; ?>.
Check your answers and rerun the configuration.</p>
</div>
<?php endif; ?>
<?php if ($internal_error): ?>
<div class="alert alert-danger" role="alert">
<p>Generating the configuration files has failed.</p>
</div>
<?php endif; ?>
<?php if ($file_error): ?>
<div class="alert alert-danger" role="alert">
<p>Writing the configuration files has failed.</p>
</div>
<?php endif; ?>
<form method="post">
<input type="hidden" name="configure_token" value="<?php echo $token; ?>" />
<div class="form-group<?php if ($missing_sitename): ?> has-error<?php endif; ?>">
<label for="configure_sitename">What is the name of the site?</label>
<span class="help-block">Specify a domain name without the <em>www</em> prefix.</span>
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_sitename" id="configure_sitename" size="30" maxlength="40" value="<?php echo htmlspecialchars($sitename, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'configure_webmaster')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-globe"></span></span>
</div>
</div>
<?php if ($missing_sitename): ?>
<p class="text-danger">Enter a domain name such as <em>izend.org</em>.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_webmaster): ?> has-error<?php endif; ?>">
<label for="configure_webmaster">What is the email address of the webmaster?</label>
<span class="help-block">The contact page will send messages to this address.</span>
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_webmaster" id="configure_webmaster" size="30" maxlength="100" value="<?php echo htmlspecialchars($webmaster, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'configure_sitename')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
</div>
</div>
<?php if ($missing_webmaster): ?>
<p class="text-danger">Specify a valid email address.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_content_languages): ?> has-error<?php endif; ?>">
<label>In what languages is the content of the site written?</label>
<span class="help-block">You will always be able to add more languages later.</span>
<div class="form-group">
<?php foreach ($system_languages as $slang): ?><?php echo PHP_EOL; ?><label class="checkbox-inline"><input name="configure_content_languages[]" type="checkbox" value="<?php echo $slang; ?>" title="<?php echo $slang; ?>"<?php if (in_array($slang, $content_languages)): ?> checked="checked"<?php endif; ?>/>&nbsp;<span class="lang-<?php echo $slang; ?>" title="<?php echo $slang; ?>"><?php echo $slang; ?></span></label><?php endforeach; ?><?php echo PHP_EOL; ?>
</div>
<?php if ($missing_content_languages): ?>
<p class="text-danger">Choose at least one language for the content of the site.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($bad_default_language): ?> has-error<?php endif; ?>">
<label>What is the default language?</label>
<div class="form-group">
<?php foreach ($system_languages as $slang): ?><?php echo PHP_EOL; ?><label class="radio-inline"><input name="configure_default_language" type="radio" value="<?php echo $slang; ?>" title="<?php echo $slang; ?>"<?php if ($slang == $default_language): ?> checked="checked"<?php endif; ?> />&nbsp;<span class="lang-<?php echo $slang; ?>" title="<?php echo $slang; ?>"><?php echo $slang; ?></span></label><?php endforeach; ?><?php echo PHP_EOL; ?>
</div>
<?php if ($bad_default_language): ?>
<p class="text-danger">You haven't mentionned this language in the previous list.</p>
<?php endif; ?>
</div>
<h6>Database</h6>
<?php if ($db_error): ?>
<div class="alert alert-danger" role="alert">
<p>The configuration of the database has failed with the error:</p>
<p><?php echo htmlspecialchars($db_error); ?></p>
<?php if ($db_flag and !$db_reuse): ?>
<?php if ($db_type == 'mysql'): ?>
<p><b>IMPORTANT</b>: Before you can retry the configuration, you must manually delete the <code><?php echo htmlspecialchars($db_name, ENT_COMPAT, 'UTF-8'); ?></code> DB
and the entries for the user <code><?php echo $db_user; ?></code> in the <i>user</i> and <i>db</i> tables of the <i>mysql</i> DB.
Terminate by executing the order FLUSH PRIVILEGES.</p>
<?php elseif ($db_type == 'pgsql'): ?>
<p><b>IMPORTANT</b>: Before you can retry the configuration, you must manually delete the <code><?php echo htmlspecialchars($db_name, ENT_COMPAT, 'UTF-8'); ?></code> DB
and the role <code><?php echo $db_user; ?></code>.</p>
<?php endif; ?>
<?php endif; ?>
</div>
<?php endif; ?>
<div class="form-group">
<label>Do you have a database server?</label>
<span class="help-block">Without a database, the functionalities will be more limited.</span>
<div class="form-group">
<label class="radio-inline"><input name="configure_db_flag" type="radio" value="yes"<?php if ($db_flag): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">yes</span></label>
<label class="radio-inline"><input name="configure_db_flag" type="radio" value="no"<?php if (!$db_flag): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">no</span></label>
</div>
</div>
<div class="form-group<?php if ($bad_db_type): ?> has-error<?php endif; ?>">
<label>Do you use MySQL or PostgreSQL?</label>
<div class="form-group">
<label class="radio-inline"><input name="configure_db_type" type="radio" value="mysql"<?php if ($db_type == 'mysql'): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">MySQL</span></label>
<label class="radio-inline"><input name="configure_db_type" type="radio" value="pgsql"<?php if ($db_type == 'pgsql'): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">PostgreSQL</span></label>
</div>
<?php if ($bad_db_type): ?>
<p class="text-danger">Check the option MySQL or the option PostgreSQL.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_db_name or $bad_db_name): ?> has-error<?php endif; ?>">
<label for="configure_db_name">What is the name of the database?</label>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="configure_db_name" id="configure_db_name" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_name, ENT_COMPAT, 'UTF-8'); ?>" />
</div>
<?php if ($missing_db_name or $bad_db_name): ?>
<p class="text-danger">Enter between 2 and 30 characters (letter, digit or underscore) starting with a letter.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_db_host or $bad_db_host): ?> has-error<?php endif; ?>">
<label for="configure_db_host">What is the name of the database host?</label>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="configure_db_host" id="configure_db_host" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_host, ENT_COMPAT, 'UTF-8'); ?>" />
</div>
<?php if ($missing_db_host or $bad_db_host): ?>
<p class="text-danger">Enter a server name or an IP address.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_db_user or $missing_db_password or $bad_db_user or $weak_db_password): ?> has-error<?php endif; ?>">
<label>What are the name and the password of the user of the database?</label>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_db_user" id="configure_db_user" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_user, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'configure_db_password')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
</div>
</div>
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_db_password" id="configure_db_password" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_password, ENT_COMPAT, 'UTF-8'); ?>" autocomplete="off" onkeypress="return focusonenter(event, 'configure_db_user')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
</div>
</div>
</div>
<?php if ($missing_db_user and $missing_db_password): ?>
<p class="text-danger">Choose an identifier for the user of the database and a password.</p>
<?php else: ?>
<?php if ($missing_db_user or $bad_db_user): ?>
<p class="text-danger">Enter between 2 and 30 characters (letter, digit or underscore) starting with a letter.</p>
<?php endif; ?>
<?php if ($missing_db_password): ?>
<p class="text-danger">Enter a password.</p>
<?php elseif ($weak_db_password): ?>
<p class="text-danger">Enter a combination of letters and digits of at least 6 characters.</p>
<?php endif; ?>
<?php endif; ?>
</div>
<div class="form-group">
<label>Do you use an existing database?</label>
<div class="form-group">
<label class="radio-inline"><input name="configure_db_reuse" type="radio" value="yes"<?php if ($db_reuse): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">yes</span></label>
<label class="radio-inline"><input name="configure_db_reuse" type="radio" value="no"<?php if (!$db_reuse): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">no</span></label>
</div>
</div>
<div class="form-group<?php if ($missing_db_admin_user or $missing_db_admin_password): ?> has-error<?php endif; ?>">
<label>If no, what are the name and the password of the administrator of the database server?</label>
<span class="help-block">This information will not be registered.</span>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_db_admin_user" id="configure_db_admin_user" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_admin_user, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'configure_db_admin_password')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
</div>
</div>
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_db_admin_password" id="configure_db_admin_password" size="30" maxlength="40" value="<?php echo htmlspecialchars($db_admin_password, ENT_COMPAT, 'UTF-8'); ?>" autocomplete="off" onkeypress="return focusonenter(event, 'configure_db_admin_user')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
</div>
</div>
</div>
<?php if ($missing_db_admin_user and $missing_db_admin_password): ?>
<p class="text-danger">Enter the identifier of the administrator of the database server followed by his password.</p>
<?php else: ?>
<?php if ($missing_db_admin_user): ?>
<p class="text-danger">Enter the identifier of the administrator of the database server.</p>
<?php endif; ?>
<?php if ($missing_db_admin_password): ?>
<p class="text-danger">Enter the password of the administrator of the database server.</p>
<?php endif; ?>
<?php endif; ?>
</div>
<div class="form-group<?php if ($bad_db_prefix): ?> has-error<?php endif; ?>">
<label for="configure_db_prefix">What is the prefix of the tables?</label>
<span class="help-block">A prefix is necessary if the database is shared.</span>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="configure_db_prefix" id="configure_db_prefix" size="10" maxlength="30" value="<?php echo htmlspecialchars($db_prefix, ENT_COMPAT, 'UTF-8'); ?>" />
</div>
<?php if ($bad_db_prefix): ?>
<p class="text-danger">Enter between 2 and 30 characters (letter, digit or underscore) starting with a letter.</p>
<?php endif; ?>
</div>
<div class="form-group<?php if ($missing_site_admin_user or $missing_site_admin_password or $bad_site_admin_user or $weak_site_admin_password): ?> has-error<?php endif; ?>">
<label>What are the name and the password of the administrator of the site?</label>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_site_admin_user" id="configure_site_admin_user" size="30" maxlength="40" value="<?php echo htmlspecialchars($site_admin_user, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'configure_site_admin_password')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
</div>
</div>
<div class="form-group form-inline-auto">
<div class="input-group">
<input type="text" class="form-control" name="configure_site_admin_password" id="configure_site_admin_password" size="30" maxlength="40" value="<?php echo htmlspecialchars($site_admin_password, ENT_COMPAT, 'UTF-8'); ?>" autocomplete="off" onkeypress="return focusonenter(event, 'configure_site_admin_user')" />
<span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
</div>
</div>
</div>
<?php if ($missing_site_admin_user and $missing_site_admin_password): ?>
<p class="text-danger">Choose an identifier for the administrator of the site and a password.</p>
<?php else: ?>
<?php if ($missing_site_admin_user or $bad_site_admin_user): ?>
<p class="text-danger">Enter between 2 and 30 characters (letter, digit or underscore) starting with a letter.</p>
<?php endif; ?>
<?php if ($missing_site_admin_password): ?>
<p class="text-danger">Enter a password.</p>
<?php elseif ($weak_site_admin_password): ?>
<p class="text-danger">Enter a combination of lowercase and uppercase letters and digits of at least 6 characters.</p>
<?php endif; ?>
<?php endif; ?>
</div>
<div class="form-group">
<button type="submit" class="btn <?php if ($bad_write_permission or $missing_sitename or $missing_webmaster or $missing_content_languages or $bad_default_language or $missing_db_admin_user or $missing_db_admin_password or $bad_db_type or $missing_db_name or $bad_db_name or $missing_db_host or $bad_db_host or $bad_db_prefix or $missing_db_user or $bad_db_user or $missing_db_password or $weak_db_password or $missing_site_admin_user or $bad_site_admin_user or $missing_site_admin_password or $weak_site_admin_password): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="configure_configure" id="configure_configure">Configure</button>
</div>
</form>
