<?php

/**
 *
 * @copyright  2012 (2017) izend.org
 * @version    3 (2)
 * @link       http://www.izend.org
 */
?>
<?php if (!empty($supported_currencies)): ?>
<?php extract($errors); ?>
<form method="post">
<input type="hidden" name="donateme_token" value="<?php echo $token; ?>" />
<div class="form-inline">
<div class="form-group form-inline-auto<?php if ($missing_amount or $bad_amount): ?> has-error<?php endif; ?>">
<input type="text" class="form-control" name="donateme_amount" id="donateme_amount" size="3" maxlength="5" title="Amount" value="<?php echo $amount; ?>" />
<?php if (count($supported_currencies) > 1): ?>
<select class="form-control" name="donateme_currency" size="1">
<?php foreach ($supported_currencies as $curr): ?>
<option value="<?php echo $curr; ?>"<?php if ($currency == $curr) : ?> selected="selected"<?php endif; ?>><?php echo $curr; ?></option>
<?php endforeach; ?>
</select>
<?php else: ?>
<input type="hidden" name="donateme_currency" value="<?php echo $supported_currencies[0]; ?>" />
<span class="form-control-static"><?php echo $supported_currencies[0]; ?></span>
<?php endif; ?>
</div>
<div class="form-group">
<button type="submit" class="btn btn-blank donate-en" name="donateme_donate" id="donateme_donate" title="PayPal - The safer, easier way to pay online!"></button>
</div>
</div>
</div>
</form>
<?php endif; ?>
<?php
$focus=false;
if ($missing_amount or $bad_amount or $missing_currency or $bad_currency) {
	$focus='#donateme_amount';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
