<?php

/**
 *
 * @copyright  2010-2014 izend.org
 * @version    12
 * @link       http://www.izend.org
 */
?>
<div id="footer">
<?php if (!empty($languages)): ?>
<?php echo $languages; ?>
<?php endif; ?>
<p>
&copy;&nbsp;<?php echo idate('Y'); ?> <?php echo $sitename, PHP_EOL; ?>
<span class="hidden">
<span class="bullet">&bull;</span>
<a href="http://www.izend.org">iZend</a>
</span>
<?php if (!empty($contact_page) or !empty($newsletter_page) or !empty($nobody_page) or !empty($account_page) or !empty($user_page) or !empty($admin_page)): ?>
<span class="hidden-print">
<?php if (!empty($contact_page)): ?>
<span class="bullet">&bull;</span>
<a href="<?php echo $contact_page; ?>" rel="nofollow" title="Contact us">Contact</a>
<?php endif; ?>
<?php if (!empty($newsletter_page)): ?>
<span class="bullet">&bull;</span>
<a href="<?php echo $newsletter_page; ?>" rel="nofollow" title="Follow us">Newsletter</a>
<?php endif; ?>
<?php if (!empty($nobody_page) or !empty($account_page) or !empty($user_page) or !empty($admin_page)): ?>
<span class="bullet">&bull;</span>
<span class="iconbar">
<?php if (!empty($nobody_page)): ?>
<a class="reverse" href="<?php echo $nobody_page; ?>" rel="nofollow" title="Quit"><span class="glyphicon glyphicon-off" aria-hidden="true"></span></a></a>
<?php endif; ?>
<?php if (!empty($account_page)): ?>
<a class="reverse" href="<?php echo $account_page; ?>" rel="nofollow" title="Your account"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a></a>
<?php endif; ?>
<?php if (!empty($user_page)): ?>
<a class="reverse" href="<?php echo $user_page; ?>" rel="nofollow" title="Your account"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a></a>
<?php endif; ?>
<?php if (!empty($admin_page)): ?>
<a class="reverse" href="<?php echo $admin_page; ?>" rel="nofollow" title="Manage"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a></a>
<?php endif; ?>
</span>
<?php endif; ?>
</span>
<?php endif; ?>
</p>
</div>
