<?php

/**
 *
 * @copyright  2010-2026 (2016-2026) izend.org
 * @version    15 (3)
 * @link       http://www.izend.org
 */
?>
<a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo rawurlencode($base_url . '/' . $request_path); ?>" target="_blank" rel="noopener noreferrer" title="Share on Facebook">
<?php switch ($sharemode): ?>
<?php case 'awesome': ?>
<i class="fab fa-facebook-f"></i>
<?php break; ?>
<?php case 'lite': ?>
<?php default: ?>
<span class="social-facebook">Facebook</span></a>
<?php break; ?>
<?php endswitch; ?>
</a>
