<?php

/**
 *
 * @copyright  2013-2018 (2018) izend.org
 * @version    6 (2)
 * @link       http://www.izend.org
 */
?>
<div id="linkbar" class="hidden-print">
<a href="https://www.facebook.com/" target="_blank" title="Join us on Facebook"><span class="link-facebook">Facebook</span></a>
<a href="https://twitter.com/" target="_blank" title="Follow us on Twitter"><span class="link-twitter">Twitter</span></a>
<a href="https://www.buzzmii.com/" target="_blank" title="Visit our page on BuZZmii"><span class="link-buzzmii">BuZZmii</span></a>
<a href="https://www.youtube.com/channel/" target="_blank" title="Watch our videos on YouTube"><span class="link-youtube">YouTube</span></a>
<a href="https://www.pinterest.com/" target="_blank" title="Look at our pins on Pinterest"><span class="link-pinterest">Pinterest</span></a>
<a href="https://www.instagram.com/" target="_blank" title="See us on Instagram"><span class="link-instagram">Instagram</span></a>
<a href="<?php echo $base_path; ?>/en/rss" title="Subscribe to the RSS feed"><span class="link-rss">RSS</span></a>
<a href="<?php echo $base_path; ?>/en/newsletter/subscribe" title="Receive our newsletter"><span class="link-newsletter">Newsletter</span></a>
</div>
