<?php

/**
 *
 * @copyright  2010-2020 (2017-2020) izend.org
 * @version    30 (9)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php extract($infos); ?>
<form method="post"<?php if ($with_attachment): ?> enctype="multipart/form-data"<?php endif; ?>>
<input type="hidden" name="mailme_token" value="<?php echo $token; ?>" />
<?php if ($with_attachment and $maxfilesize): ?>
<input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $maxfilesize; ?>" />
<?php endif; ?>
<div class="form-group<?php if ($missing_mail or $bad_mail): ?> has-error<?php endif; ?>">
<label for="mailme_mail">What is your email address?</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="mailme_mail" id="mailme_mail" size="40" maxlength="100" spellcheck="false" placeholder="Email" value="<?php echo htmlspecialchars($mail, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'mailme_subject')" />
</div>
<span class="help-block">Your email address is strictly confidential.</span>
</div>
<div class="form-group<?php if ($missing_subject or $bad_subject or $missing_message): ?> has-error<?php endif; ?>">
<label for="mailme_subject">Type in the subject and the text of your message:</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="mailme_subject" id="mailme_subject" size="40" maxlength="100" placeholder="Subject" value="<?php echo htmlspecialchars($subject, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'mailme_message')" />
</div>
</div>
<div class="form-group form-inline-auto<?php if ($missing_message): ?> has-error<?php endif; ?>">
<textarea class="form-control" name="mailme_message" id="mailme_message" cols="60" rows="5" placeholder="Text"><?php echo htmlspecialchars($message, ENT_COMPAT, 'UTF-8'); ?></textarea>
</div>
<?php if ($with_attachment): ?>
<div class="form-group">
<input type="file" name="mailme_file" id="mailme_file" title="" />
</div>
<div class="form-group hidden">
<button type="submit" class="btn <?php if ($bad_attachment): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="mailme_put" id="mailme_put">Add</button>
<span class="form-control-static">
an attachment
<span class="glyphicon glyphicon-paperclip"></span>
</span>
<?php if ($maxfilesize): ?>
<?php require_once 'countformat.php'; ?>
<span class="help-block">You can attach a file &lt; <?php echo count_format($maxfilesize, '.', ''); ?> bytes.</span>
<?php endif; ?>
</div>
<?php endif; ?>
<?php if ($with_appointment): ?>
<div class="form-group form-inline<?php if ($bad_appointment): ?> has-error<?php endif; ?>">
<div class="form-group form-inline-auto">
<span class="form-control-static"><strong>Appointment on</strong></span>
<input type="text" class="form-control" name="mailme_date" id="mailme_date" size="10" placeholder="yyyy-mm-dd" value="<?php echo htmlspecialchars($date, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'mailme_code')" />
</div>
<div class="form-group form-inline-auto">
<span class="form-control-static"><strong>at</strong></span>
<select class="form-control" id="mailme_hour" name="mailme_hour" size="1">
<?php foreach (range(8, 18, 1) as $hh): ?>
<option value="<?php echo $hh; ?>"<?php if ($hour == $hh): ?> selected="selected"<?php endif; ?>><?php echo $hh > 9 ? $hh : '0' . $hh; ?></option>
<?php endforeach; ?>
</select>
<span class="form-control-static"><strong>:</strong></span>
<select class="form-control" id="mailme_minute" name="mailme_minute" size="1">
<?php foreach (range(0, 45, 15) as $mm): ?>
<option value="<?php echo $mm; ?>"<?php if ($minute == $mm): ?> selected="selected"<?php endif; ?>><?php echo $mm > 0 ? $mm : '0' . $mm; ?></option>
<?php endforeach; ?>
</select>
</div>
</div>
<?php endif; ?>
<?php if ($with_captcha): ?>
<div class="form-group form-inline<?php if ($missing_code or $bad_code): ?> has-error<?php endif; ?>">
<div class="form-group form-inline-auto">
<img class="captcha" src="<?php echo $base_path; ?>/captcha/mailme" alt="" height="40" title="Verification code" />
<span class="form-control-static">:</span>
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="mailme_code" id="mailme_code" size="4" maxlength="4" title="4 letters" value="" autocomplete="off" onkeypress="return submitonenter(event, 'mailme_send')" />
</div>
</div>
<?php endif; ?>
<div class="form-group">
<button type="submit" class="btn <?php if ($internal_error or $missing_code or $bad_code or $missing_mail or $bad_mail or $missing_subject or $bad_subject or $missing_message or $bad_appointment or $bad_attachment): ?>btn-danger<?php elseif ($email_sent): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="mailme_send" id="mailme_send">Send</button>
</div>
</form>
<?php if ($missing_code): ?>
<p class="text-danger">Enter the verification code displayed in the image.</p>
<?php elseif ($bad_code): ?>
<p class="text-danger">The verification code is incorrect.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p class="text-danger">An internal error has occurred.</p>
<?php endif; ?>
<?php if ($email_sent): ?>
<p>Your message has been sent to the webmaster.
<?php if ($home_page): ?>
To return to the home page, <a class="clickhere" href="<?php echo $home_page; ?>">click here</a>.
<?php endif; ?>
</p>
<?php endif; ?>
<?php if ($with_attachment): ?>
<script>
(function() {
	var file=$('#mailme_file');
	var upload=$('#mailme_put');

	upload.parent().removeClass('hidden');

	file.css({ position: 'absolute', left: '-9999px' });

	upload.on('click', function(e) { e.preventDefault(); file.click(); });

	file.change(function() {
		if (file.val()) {
			upload.removeClass('btn-default').removeClass('btn-danger').addClass('btn-success');
		}
	});
})();
</script>
<?php endif; ?>
<?php if ($with_appointment): ?>
<?php head('javascript', 'jquery-ui'); ?>
<?php head('stylesheet', 'jquery-ui', 'screen'); ?>
<script>
$('#mailme_date').datepicker({dateFormat: 'yy-mm-dd', autoSize: true, showAnim: 'drop', showOn: 'both', buttonText: 'Calendar', buttonImage: '/images/theme/edit/calendar.png', buttonImageOnly: true, minDate: '+1d', maxDate: '+2m', showOtherMonths: true, navigationAsDateFormat: true, prevText: 'MM', nextText: 'MM', beforeShowDay: function(date) {return [date.getDay() != 0];}});
</script>
<?php endif; ?>
<?php
$focus=false;
if ($missing_code or $bad_code) {
	$focus='#mailme_code';
}
else if ($missing_mail or $bad_mail) {
	$focus='#mailme_mail';
}
else if ($missing_subject or $bad_subject) {
	$focus='#mailme_subject';
}
else if ($missing_message) {
	$focus='#mailme_message';
}
else if ($bad_appointment) {
	$focus='#mailme_date';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
