<?php

/**
 *
 * @copyright  2012-2018 (2016) izend.org
 * @version    5 (1)
 * @link       http://www.izend.org
 */
?>
<?php require_once 'dateen.php'; ?>
<div id="newsletterpage">
<h3><?php echo htmlspecialchars($page_title ? $page_title : $page_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<?php if ($next_page_url or $prev_page_url): ?>
<p>
<?php if ($prev_page_url): ?>
&larr;&nbsp;<a href="<?php echo $prev_page_url; ?>"><?php echo htmlspecialchars($prev_page_label, ENT_COMPAT, 'UTF-8'); ?></a>
<?php endif; ?>
<?php if ($next_page_url and $prev_page_url): ?>
&nbsp;|&nbsp;
<?php endif; ?>
<?php if ($next_page_url): ?>
<a href="<?php echo $next_page_url; ?>"><?php echo htmlspecialchars($next_page_label, ENT_COMPAT, 'UTF-8'); ?></a>&nbsp;&rarr;
<?php endif; ?>
</p>
<?php endif; ?>
<p><?php echo longdatetime_en($page_modified); ?></p>
<?php if ($postnews): ?>
<?php echo $postnews; ?>
<?php endif; ?>
<?php if ($message_html): ?>
<div id="newsletterpage_html">
<?php echo $message_html; ?>
</div>
<?php endif; ?>
<?php if ($message_text): ?>
<div id="newsletterpage_text">
<pre><code><?php echo $message_text; ?></code></pre>
</div>
<?php endif; ?>
<?php if ($with_mail): ?>
<form method="post">
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn <?php if ($missing_mail or $bad_mail): ?>btn-danger<?php elseif ($email_sent): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="newsletterpage_send" id="newsletterpage_send">Send</button>
<span class="form-control-static">to</span>
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="newsletterpage_mailto" id="newsletterpage_mailto" size="30" maxlength="100" placeholder="Email" value="<?php echo htmlspecialchars($mailto, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'newsletterpage_send')" />
</div>
</div>
</form>
<?php endif; ?>
<?php if ($email_sent): ?>
<p>The message has been sent to <i><?php echo $mailto; ?></i>.</p>
<?php endif; ?>
<?php
$focus=false;
if ($missing_mail or $bad_mail) {
	$focus='#newsletterpage_mailto';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
</div>
