<?php

/**
 *
 * @copyright  2012-2022 (2016-2022) izend.org
 * @version    11 (3)
 * @link       http://www.izend.org
 */
?>
<?php if ($mailed): ?>
<?php require_once 'dateen.php'; ?>
<p id="newsletterpage_status"><img src="/images/theme/envelopesmall.png" alt="" />
The message was sent <b><?php echo longdate_en($mailed); ?></b> at <b><?php echo date('H:i', $mailed); ?></b>.</p>
<?php elseif ($scheduled): ?>
<?php require_once 'dateen.php'; ?>
<form method="post">
<input type="hidden" name="postnews_token" value="<?php echo $token; ?>" />
<div class="form-group form-inline">
<button type="submit" class="btn <?php if ($internal_error): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="postnews_cancel" id="postnews_cancel">Cancel</button>
<span class="form-control-static">sending the message <b><?php echo longdate_en($scheduled); ?></b> at <b><?php echo date('H:i', $scheduled); ?></b></span>
</div>
</form>
<?php else: ?>
<?php extract($errors); ?>
<?php
$date=date('Y-m-d', $postdate);
$hour=idate('H', $postdate);
$minute=idate('i', $postdate);
?>
<form method="post">
<input type="hidden" name="postnews_token" value="<?php echo $token; ?>" />
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<button type="submit" class="btn <?php if ($internal_error or $missing_date or $bad_date): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="postnews_post" id="postnews_post">Post</button>
<input type="text" class="form-control" name="postnews_date" id="postnews_date" size="10" placeholder="aaaa-mm-jj" value="<?php if ($date): ?><?php echo htmlspecialchars($date, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" />
</div>
<div class="form-group form-inline-auto">
<span class="form-control-static">at</span>
<select class="form-control" id="postnews_hour" name="postnews_hour" size="1">
<?php foreach (range($hmin, $hmax, 1) as $hh): ?>
<option value="<?php echo $hh; ?>"<?php if ($hour == $hh): ?> selected="selected"<?php endif; ?>><?php echo $hh > 9 ? $hh : '0' . $hh; ?></option>
<?php endforeach; ?>
</select>
<span class="form-control-static">:</span>
<select class="form-control" id="postnews_minute" name="postnews_minute" size="1">
<?php foreach (range(0, 45, 15) as $mm): ?>
<option value="<?php echo $mm; ?>"<?php if ($minute == $mm): ?> selected="selected"<?php endif; ?>><?php echo $mm > 0 ? $mm : '0' . $mm; ?></option>
<?php endforeach; ?>
</select>
</div>
</div>
</form>
<?php head('javascript', 'jquery-ui'); ?>
<?php head('stylesheet', 'jquery-ui', 'screen'); ?>
<script>
$('#postnews_date').datepicker({dateFormat: 'yy-mm-dd', autoSize: true, showAnim: 'drop', showOn: 'both', buttonText: 'Calendar', buttonImage: '/images/theme/edit/calendar.png', buttonImageOnly: true, minDate: '+0d', maxDate: '+1m', showOtherMonths: true, navigationAsDateFormat: true, prevText: 'MM', nextText: 'MM'});
</script>
<?php
$focus=false;
if ($bad_date) {
	$focus='#postnews_date';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
<?php endif; ?>
