<?php

/**
 *
 * @copyright  2010-2018 (2017 izend.org
 * @version    15 (2)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php extract($infos); ?>
<form method="post">
<input type="hidden" name="remindme_token" value="<?php echo $token; ?>" />
<div class="form-group<?php if ($missing_login or $bad_login): ?> has-error<?php endif; ?>">
<label for="remindme_login"><?php if ($with_name): ?>What is your connection name?<?php else: ?>What is your email address?<?php endif; ?></label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="remindme_login" id="remindme_login" size="40" maxlength="100" placeholder="<?php if ($with_name): ?>Identifier<?php else: ?>name@domain.net<?php endif; ?>" value="<?php echo htmlspecialchars($login, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'remindme_code')" />
</div>
<?php if ($with_name): ?>
<span class="help-block">You may also enter your email address.</span>
<?php endif; ?>
</div>
<div class="checkbox<?php if ($missing_confirmation): ?> has-error<?php endif; ?>">
<label><input type="checkbox" name="remindme_confirmed" id="remindme_confirmed" title="Confirmation"<?php if ($confirmed): ?> checked="checked"<?php endif; ?> />&nbsp;I want to receive a new password</label>
</div>
<?php if ($with_captcha): ?>
<div class="form-group form-inline<?php if ($missing_code or $bad_code): ?> has-error<?php endif; ?>">
<div class="form-group form-inline-auto">
<img class="captcha" src="<?php echo $base_path; ?>/captcha/remindme" alt="" height="40" title="Verification code" />
<span class="form-control-static">:</span>
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="remindme_code" id="remindme_code" size="4" maxlength="4" title="4 letters" value="" autocomplete="off" onkeypress="return submitonenter(event, 'remindme_send')" />
</div>
</div>
<?php endif; ?>
<div class="form-group">
<button type="submit" class="btn <?php if ($internal_error or $missing_code or $bad_code or $missing_login or $bad_login or $missing_confirmation): ?>btn-danger<?php elseif ($email_sent): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="remindme_send" id="remindme_send">Send</button>
</div>
</form>
<?php if ($missing_code): ?>
<p class="text-danger">Enter the verification code displayed in the image.</p>
<?php elseif ($bad_code): ?>
<p class="text-danger">The verification code is incorrect.</p>
<?php endif; ?>
<?php if ($missing_confirmation): ?>
<p class="text-danger">Check the confirmation box.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>An internal error has occurred.
<?php if ($contact_page): ?>If you can describe the problem, please <a href="<?php echo $contact_page; ?>" rel="nofollow">contact us</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($email_sent): ?>
<p>A new password has been sent to you by email.
To identify yourself, <a class="clickhere" href="<?php echo $user_page; ?>">click here</a>.</p>
<?php endif; ?>
<?php
$focus=false;
if ($missing_code or $bad_code) {
	$focus='#remindme_code';
}
else if ($missing_login or $bad_login) {
	$focus='#remindme_login';
}
else if ($missing_confirmation) {
	$focus='#remindme_code';
}
?>
<?php if ($focus): ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
