<?php

/**
 *
 * @copyright  2012-2018 (2016) izend.org
 * @version    12 (1)
 * @link       http://www.izend.org
 */
?>
<div id="socialbar" class="hidden-print">
<a href="https://www.facebook.com/pages/" target="_blank" title="Join us on Facebook"><span class="social-facebook">Facebook</span></a>
<a href="https://twitter.com/#!/" target="_blank" title="Follow us on Twitter"><span class="social-twitter">Twitter</span></a>
<a href="https://plus.google.com/" target="_blank" title="Stay in touch with Google+"><span class="social-gplus">Google+</span></a>
<a href="http://www.linkedin.com/" target="_blank" title="Connect to our network on LinkedIn"><span class="social-linkedin">LinkedIn</span></a>
<a href="https://www.youtube.com/channel/" target="_blank" title="Watch our videos on YouTube"><span class="social-youtube">YouTube</span></a>
<a href="https://www.pinterest.com/" target="_blank" title="Look at our pins on Pinterest"><span class="social-pinterest">Pinterest</span></a>
<a href="<?php echo $base_path; ?>/en/rss" target="_blank" rel="nofollow" title="Subscribe to the RSS feed"><span class="social-rss">RSS</span></a>
<a href="<?php echo $base_path; ?>/en/newsletter/subscribe" rel="nofollow" title="Receive our newsletter"><span class="social-newsletter">Newsletter</span></a>
</div>
