<?php

/**
 *
 * @copyright  2012-2020 (2016-2020) izend.org
 * @version    15 (3)
 * @link       http://www.izend.org
 */
?>
<div id="socialbar" class="hidden-print">
<a href="https://www.facebook.com/pages/" title="Join us on Facebook"><span class="social-facebook">Facebook</span></a>
<a href="https://twitter.com/#!/" title="Follow us on Twitter"><span class="social-twitter">Twitter</span></a>
<a href="http://www.linkedin.com/" title="Connect to our network on LinkedIn"><span class="social-linkedin">LinkedIn</span></a>
<a href="https://www.youtube.com/channel/" title="Watch our videos on YouTube"><span class="social-youtube">YouTube</span></a>
<a href="https://www.pinterest.com/" title="Look at our pins on Pinterest"><span class="social-pinterest">Pinterest</span></a>
<a href="<?php echo $base_path; ?>/en/rss" rel="nofollow" title="Subscribe to the RSS feed"><span class="social-rss">RSS</span></a>
<a href="<?php echo $base_path; ?>/en/newsletter/subscribe" rel="nofollow" title="Receive our newsletter"><span class="social-newsletter">Newsletter</span></a>
<a href="<?php echo $base_path; ?>/en/contact" rel="nofollow" title="Contact us"><span class="social-email">Email</span></a>
</div>
