<?php

/**
 *
 * @copyright  2011-2022 (2017-2022) izend.org
 * @version    27 (7)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<?php extract($infos); ?>
<form method="post">
<input type="hidden" name="useredit_token" value="<?php echo $token; ?>" />
<?php if ($user_accessed): ?>
<input type="hidden" name="useredit_accessed" value="<?php echo $user_accessed; ?>" />
<?php endif; ?>
<?php if ($with_info): ?>
<div class="form-group<?php if ($missing_firstname): ?> has-error<?php endif; ?>">
<label for="useredit_firstname">First name</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_firstname" id="useredit_firstname" size="30" maxlength="100" placeholder="Fist name" value="<?php echo htmlspecialchars($user_firstname, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'useredit_lastname')" />
</div>
</div>
<div class="form-group<?php if ($missing_lastname): ?> has-error<?php endif; ?>">
<label for="useredit_lastname">Last name</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_lastname" id="useredit_lastname" size="30" maxlength="100" placeholder="Last name" value="<?php echo htmlspecialchars($user_lastname, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, '<?php echo $with_name ? 'useredit_name' : 'useredit_mail'; ?>')" />
</div>
</div>
<?php endif; ?>
<?php if ($with_name): ?>
<div class="form-group<?php if ($missing_name or $bad_name or $duplicated_name): ?> has-error<?php endif; ?>">
<label for="useredit_name">Identifier</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_name" id="useredit_name" size="20" maxlength="20" placeholder="2 to 20 letters" value="<?php echo htmlspecialchars($user_name, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'useredit_mail')" />
<img class="hidden-xxs" src="<?php echo $base_path; ?>/avatars/<?php echo $user_name; ?>.png" alt="" width="24" height="24" title="<?php echo $user_name; ?>" />
</div>
</div>
<?php else: ?>
<input type="hidden" name="useredit_name" value="<?php echo htmlspecialchars($user_name, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<div class="form-group<?php if ($missing_mail or $bad_mail or $duplicated_mail): ?> has-error<?php endif; ?>">
<label for="useredit_mail">Email</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_mail" id="useredit_mail" size="30" maxlength="100" placeholder="name@domain.net" value="<?php echo htmlspecialchars($user_mail, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'useredit_modify')" />
</div>
</div>
<?php if ($with_role): ?>
<div class="form-group">
<?php $rolename=array('administrator' => 'administrator', 'writer' => 'writer', 'reader' => 'reader', 'moderator' => 'moderator'); ?>
<?php foreach ($supported_roles as $role): ?><label class="checkbox-inline"><input type="checkbox" name="useredit_role[]" value="<?php echo $role; ?>"<?php if ($user_role and in_array($role, $user_role)):?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;<?php echo $rolename[$role]; ?></span></label><?php echo PHP_EOL; ?><?php endforeach; ?>
</div>
<?php endif; ?>
<?php if ($with_website): ?>
<div class="form-group<?php if ($bad_website): ?> has-error<?php endif; ?>">
<label for="useredit_website">Website</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_website" id="useredit_website" size="30" maxlength="100" placeholder="www.domaine.com" value="<?php echo htmlspecialchars($user_website, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'useredit_modify')" />
</div>
</div>
<?php else: ?>
<input type="hidden" name="useredit_website" value="<?php echo htmlspecialchars($user_website, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<?php if ($with_timezone): ?>
<div class="form-group<?php if ($bad_timezone): ?> has-error<?php endif; ?>">
<label for="useredit_timezone">Time zone</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_timezone" id="useredit_timezone" size="30" maxlength="100" placeholder="America/Chicago" value="<?php echo htmlspecialchars($user_timezone, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'useredit_modify')" />
</div>
</div>
<?php else: ?>
<input type="hidden" name="useredit_timezone" value="<?php echo htmlspecialchars($user_timezone, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<?php if ($with_locale): ?>
<div class="form-group">
<?php foreach ($system_languages as $lang): ?><label class="radio-inline"><input type="radio" name="useredit_locale" value="<?php echo $lang; ?>" title="<?php echo $lang; ?>"<?php if ($lang == $user_locale): ?> checked="checked"<?php endif; ?> />&nbsp;<span class="lang-<?php echo $lang; ?>" title="<?php echo $lang; ?>"><?php echo $lang; ?></span></label><?php echo PHP_EOL; ?><?php endforeach; ?>
</div>
<?php else: ?>
<input type="hidden" name="useredit_locale" value="<?php echo htmlspecialchars($user_locale, ENT_COMPAT, 'UTF-8'); ?>" />
<?php endif; ?>
<?php if ($with_status): ?>
<div class="form-group">
<fieldset id="useredit_status">
<legend>Status</legend>
<label class="checkbox-inline">
<input type="checkbox" name="useredit_active"<?php if ($user_active): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;active</span>
</label>
<label class="checkbox-inline">
<input type="checkbox" name="useredit_banned"<?php if ($user_banned): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;banned</span>
</label>
<label class="checkbox-inline">
<input type="checkbox" name="useredit_confirmed"<?php if ($user_confirmed): ?> checked="checked"<?php endif; ?> /><span class="form-control-static">&nbsp;confirmed</span>
</label>
</fieldset>
</div>
<?php if ($user_accessed): ?>
<?php require_once 'dateen.php'; ?>
<p><small>Last access <?php echo longdate_en($user_accessed); ?> at <?php echo date('H:i', $user_accessed); ?></small></p>
<?php endif; ?>
<?php endif; ?>
<div class="form-group">
<?php if ($with_delete): ?>
<?php if ($confirm_delete): ?>
<button type="submit" class="btn btn-warning" name="useredit_confirmdelete" id="useredit_confirmdelete">Confirm</button>
<span class="form-control-static">delete or</span>
<button type="submit" class="btn btn-default" name="useredit_cancel" id="useredit_cancel">Cancel</button>
<?php else: ?>
<button type="submit" class="btn <?php if ($internal_error or $missing_name or $bad_name or $duplicated_name or $missing_mail or $bad_mail or $duplicated_mail or $bad_role or $bad_website or $bad_timezone or $missing_locale or $bad_locale or $missing_lastname or $missing_firstname): ?>btn-danger<?php elseif ($account_modified): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="useredit_modify" id="useredit_modify">Modify</button>
<span class="form-control-static">the profile or</span>
<button type="submit" class="btn btn-default" name="useredit_delete" id="useredit_delete">Delete</button>
<span class="form-control-static">the account</span>
<?php endif; ?>
<?php else: ?>
<button type="submit" class="btn <?php if ($internal_error or $missing_name or $bad_name or $duplicated_name or $missing_mail or $bad_mail or $duplicated_mail or $bad_role or $bad_website or $bad_timezone or $missing_locale or $bad_locale or $missing_lastname or $missing_firstname): ?>btn-danger<?php elseif ($account_modified): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="useredit_modify" id="useredit_modify">Modify</button>
<?php endif; ?>
</div>
<?php if ($with_newpassword): ?>
<?php if ($with_oldpassword): ?>
<div class="form-group<?php if ($missing_oldpassword or $bad_oldpassword): ?> has-error<?php endif; ?>">
<label for="useredit_oldpassword">Current password</label>
<div class="form-inline-auto">
<input type="password" class="form-control" name="useredit_oldpassword" id="useredit_oldpassword" size="20" maxlength="20" placeholder="6 letters and digits" title="at least 6 letters and digits" onkeypress="return focusonenter(event, 'useredit_newpassword')" /><?php if ($with_viewpassword): ?>&nbsp;<span class="glyphicon glyphicon-eye-open cursor-pointer" aria-hidden="true"></span><?php endif; ?>
</div>
</div>
<?php endif; ?>
<div class="form-group<?php if ($missing_newpassword or $bad_newpassword): ?> has-error<?php endif; ?>">
<label for="useredit_newpassword">New password</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="useredit_newpassword" id="useredit_newpassword" size="20" maxlength="20" placeholder="6 letters and digits" title="at least 6 letters and digits" value="<?php echo htmlspecialchars($user_newpassword, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'useredit_change')" />
</div>
</div>
<div class="form-group">
<button type="submit" class="btn <?php if ($internal_error or $missing_newpassword or $bad_newpassword): ?>btn-danger<?php elseif ($password_changed): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="useredit_change" id="useredit_change">Change</button>
</div>
<?php endif; ?>
</form>
<?php if ($with_newpassword and $with_oldpassword and $with_viewpassword): ?>
<script>
(function() {
	const password = document.getElementById('useredit_oldpassword');
	password.nextElementSibling.addEventListener('click', () => password.type = password.type == 'password' ? 'text' : 'password');
})();
</script>
<?php endif; ?>
<?php if ($missing_lastname and $missing_firstname): ?>
<p class="text-danger">A last name and a first name are required.</p>
<?php else: ?>
<?php if ($missing_lastname): ?>
<p class="text-danger">A last name is required.</p>
<?php endif; ?>
<?php if ($missing_firstname): ?>
<p class="text-danger">A first name is required.</p>
<?php endif; ?>
<?php endif; ?>
<?php if ($missing_name): ?>
<p class="text-danger">An identifier is required.</p>
<?php elseif ($bad_name): ?>
<p class="text-danger">An identifier must contain between 2 and 20 letters.</p>
<?php elseif ($duplicated_name): ?>
<p class="text-danger">This identifier is already taken.</p>
<?php endif; ?>
<?php if ($missing_mail): ?>
<p class="text-danger">An email address is required.</p>
<?php elseif ($bad_mail): ?>
<p class="text-danger">The email address is invalid.</p>
<?php elseif ($duplicated_mail): ?>
<p class="text-danger">This email address is already being used.</p>
<?php endif; ?>
<?php if ($bad_timezone): ?>
<p class="text-danger">The time zone is incorrect.</p>
<?php endif; ?>
<?php if ($bad_website): ?>
<p class="text-danger">The URL of the website is invalid.</p>
<?php endif; ?>
<?php if ($missing_newpassword or $bad_newpassword or $missing_oldpassword or $bad_oldpassword): ?>
<p class="text-danger">Enter a combination of letters and digits of at least 6 characters.</p>
<?php endif; ?>
<?php if ($internal_error): ?>
<p>An internal error has occurred.
<?php if ($contact_page): ?>If you can describe the problem, please <a href="<?php echo $contact_page; ?>" rel="nofollow">contact us</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($account_modified): ?>
<p>The account information has been modified.</p>
<?php endif; ?>
<?php if ($password_changed): ?>
<p>The password was changed.</p>
<?php endif; ?>
<?php
$focus=false;
if ($missing_firstname) {
	$focus='#useredit_firstname';
}
else if ($missing_lastname) {
	$focus='#useredit_lastname';
}
else if ($missing_name or $bad_name or $duplicated_name) {
	$focus='#useredit_name';
}
else if ($missing_mail or $bad_mail or $duplicated_mail) {
	$focus='#useredit_mail';
}
else if ($bad_timezone) {
	$focus='#useredit_timezone';
}
else if ($bad_website) {
	$focus='#useredit_website';
}
else if ($missing_oldpassword or $bad_oldpassword) {
	$focus='#useredit_oldpassword';
}
else if ($missing_newpassword or $bad_newpassword) {
	$focus=$with_oldpassword ? '#useredit_oldpassword' : '#useredit_newpassword';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
