<?php

/**
 *
 * @copyright  2022 (2022) izend.org
 * @version    3 (3)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<form method="post">
<input type="hidden" name="userpassword_token" value="<?php echo $token; ?>" />
<?php if ($with_oldpassword): ?>
<div class="form-group<?php if ($missing_oldpassword or $bad_oldpassword): ?> has-error<?php endif; ?>">
<label for="userpassword_oldpassword">Current password</label>
<div class="form-inline-auto">
<input type="password" class="form-control" name="userpassword_oldpassword" id="userpassword_oldpassword" size="20" maxlength="20" placeholder="6 letters and digits" title="at least 6 letters and digits" onkeypress="return focusonenter(event, 'userpassword_newpassword')" /><?php if ($with_viewpassword): ?>&nbsp;<span class="glyphicon glyphicon-eye-open cursor-pointer" aria-hidden="true"></span><?php endif; ?>
</div>
</div>
<?php endif; ?>
<div class="form-group<?php if ($missing_newpassword or $bad_newpassword): ?> has-error<?php endif; ?>">
<label for="userpassword_newpassword">New password</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="userpassword_newpassword" id="userpassword_newpassword" size="20" maxlength="20" placeholder="6 letters and digits" title="at least 6 letters and digits" value="<?php if ($newpassword): ?><?php echo htmlspecialchars($newpassword, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return submitonenter(event, 'userpassword_change')" />
</div>
</div>
<div class="infos">
<?php if ($with_oldpassword): ?>
<p class="info">Enter the current password and a new password to change it.</p>
<?php else: ?>
<p class="info">Enter a new password to change it.</p>
<?php endif; ?>
</div>
<div class="form-group">
<button type="submit" class="btn <?php if ($internal_error or $missing_newpassword or $bad_newpassword): ?>btn-danger<?php elseif ($password_changed): ?>btn-success<?php else: ?>btn-default<?php endif; ?>" name="userpassword_change" id="userpassword_change">Change</button>
</div>
</form>
<?php if ($with_oldpassword and $with_viewpassword): ?>
<script>
(function() {
	const password = document.getElementById('userpassword_oldpassword');
	password.nextElementSibling.addEventListener('click', () => password.type = password.type == 'password' ? 'text' : 'password');
})();
</script>
<?php endif; ?>
<div class="errors">
<?php if ($missing_oldpassword or $bad_oldpassword): ?>
<p>Access denied.</p>
<?php elseif ($missing_newpassword or $bad_newpassword): ?>
<p>Enter a combination of letters and digits of at least 6 characters.</p>
<?php endif; ?>
</div>
<?php extract($infos); ?>
<div class="infos">
<?php if ($internal_error): ?>
<p>An internal error has occurred.
<?php if ($contact_page): ?>If you can describe the problem, please <a href="<?php echo $contact_page; ?>" rel="nofollow">contact us</a>.<?php endif; ?></p>
<?php endif; ?>
<?php if ($password_changed): ?>
<p>The password was changed.
To identify yourself, <a class="clickhere" href="<?php echo $user_page; ?>">click here</a>.</p>
<?php endif; ?>
</div>
<?php
$focus=false;
if ($missing_oldpassword or $bad_oldpassword) {
	$focus='#userpassword_oldpassword';
}
else if ($missing_newpassword or $bad_newpassword) {
	$focus=$with_oldpassword ? '#userpassword_oldpassword' : '#userpassword_newpassword';
}
?>
<?php if ($focus): ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus();});
</script>
<?php endif; ?>
