<?php

/**
 *
 * @copyright  2010-2012 (2016) izend.org
 * @version    5 (1)
 * @link       http://www.izend.org
 */
?>
<!DOCTYPE html>
<html<?php if (!empty($lang)): ?> lang="<?php echo $lang; ?>"<?php endif; ?>>
<head>
<?php echo $head; ?>
</head>
<body>
<div class="container">
<?php echo $banner; ?>
<?php if (!empty($sidebar)): ?>
<?php echo $sidebar; ?>
<?php endif; ?>
<?php echo $content; ?>
</div>
</body>
</html>
