<?php

/**
 *
 * @copyright  2010-2026 (2016) izend.org
 * @version    20 (2)
 * @link       http://www.izend.org
 */
?>
<!DOCTYPE html>
<html<?php if (!empty($lang)): ?> lang="<?php echo $lang; ?>"<?php endif; ?>>
<head>
<?php echo $head; ?>
<?php global $googleanalyticsid, $googleanalyticspageview; ?>
<?php if (!empty($googleanalyticsid)): ?>
<script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo $googleanalyticsid; ?>"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '<?php echo $googleanalyticsid; ?>', {'page_path': '/<?php echo $googleanalyticspageview ? $googleanalyticspageview : $request_path; ?>'});
</script>
<?php endif; ?>
<?php global $pinterestassets; ?>
<?php if ($pinterestassets): ?>
<script async defer src="https://assets.pinterest.com/js/pinit.js"></script>
<?php endif; ?>
</head>
<body>
<?php if (!empty($trace)): ?>
<div>
<?php foreach ($trace as $s): ?>
<?php echo $s; ?>
<?php endforeach; ?>
</div>
<?php endif; ?>
<?php $type='standard'; ?>
<?php if ($type == 'static' or $type == 'fixed'): ?>
<?php echo $banner; ?>
<?php endif; ?>
<div class="container">
<?php if (! ($type == 'static' or $type == 'fixed')): ?>
<?php echo $banner; ?>
<?php endif; ?>
<?php if (!empty($sidebar)): ?>
<?php echo $sidebar; ?>
<?php endif; ?>
<?php echo $content; ?>
<?php if (!empty($footer)): ?>
<?php echo $footer; ?>
<?php endif; ?>
</div>
</body>
</html>
