<?php

/**
 *
 * @copyright  2010-2016 (2016) izend.org
 * @version    5 (2)
 * @link       http://www.izend.org
 */
?>
<!DOCTYPE html>
<html<?php if (!empty($lang)): ?> lang="<?php echo $lang; ?>"<?php endif; ?>>
<head>
<?php echo $head; ?>
</head>
<body>
<?php if (!empty($trace)): ?>
<?php foreach ($trace as $s): ?>
<?php echo $s; ?>
<?php endforeach; ?>
<?php endif; ?>
<?php $type='standard'; ?>
<?php if ($type == 'static' or $type == 'fixed'): ?>
<?php echo $banner; ?>
<?php endif; ?>
<div class="container">
<?php if (! ($type == 'static' or $type == 'fixed')): ?>
<?php echo $banner; ?>
<?php endif; ?>
<?php if (!empty($sidebar)): ?>
<?php echo $sidebar; ?>
<?php endif; ?>
<?php echo $content; ?>
</div>
</body>
</html>
