<?php

/**
 *
 * @copyright  2010-2022 (2016-2022) izend.org
 * @version    26 (4)
 * @link       http://www.izend.org
 */
?>
<?php if($content_types or $node_contents): ?>
<?php extract($errors); ?>
<form method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<span id="nodecontent_hidy" class="hidy"></span>
<div class="form-group">
<?php if ($content_types): ?>
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn <?php if ($missing_new_content_type or $bad_new_content_type or $bad_new_content_number): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="content_create" id="content_create">Add</button>
<span class="form-control-static">a type</span>
</div>
<?php
$selected=$new_content_type ? $new_content_type : $content_types[0];
?>
<div class="form-group form-inline-auto">
<select class="form-control" name="content_new_type" size="1">
<?php foreach ($content_types as $type): ?>
<?php if ($type == 'text'): ?>
<option value="text" <?php echo $selected == 'text' ? 'selected="selected"' : ''; ?>>Text</option>
<?php elseif ($type == 'infile'): ?>
<option value="infile" <?php echo $selected == 'infile' ? 'selected="selected"' : ''; ?>>Insertion</option>
<?php elseif ($type == 'download'): ?>
<option value="download" <?php echo $selected == 'download' ? 'selected="selected"' : ''; ?>>Download</option>
<?php elseif ($type == 'file'): ?>
<option value="file" <?php echo $selected == 'file' ? 'selected="selected"' : ''; ?>>File</option>
<?php elseif ($type == 'youtube'): ?>
<option value="youtube" <?php echo $selected == 'youtube' ? 'selected="youtube"' : ''; ?>>YouTube</option>
<?php elseif ($type == 'longtail'): ?>
<option value="longtail" <?php echo $selected == 'longtail' ? 'selected="selected"' : ''; ?>>LongTail</option>
<?php endif; ?>
<?php endforeach; ?>
</select>
<?php if ($node_contents): ?>
<span class="form-control-static">#</span>
<input type="text" class="form-control" name="content_new_number" id="content_new_number" size="2" maxlength="3" value="<?php if ($new_content_number): ?><?php echo htmlspecialchars($new_content_number, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
<?php endif; ?>
</div>
<?php endif; ?>
<?php if ($node_contents): ?>
<?php if ($content_types) :?>
<div class="form-group form-inline-auto">
<div class="form-group">
<span class="form-control-static ">or</span>
</div>
<?php endif; ?>
<button type="submit" class="btn <?php if ($missing_old_content_number or $bad_old_content_number): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="content_delete" id="content_delete">Delete</button>
<span class="form-control-static">#</span>
<input type="text" class="form-control" name="content_old_number" id="content_old_number" size="2" maxlength="3" placeholder="" value="<?php if ($old_content_number): ?><?php echo htmlspecialchars($old_content_number, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
<?php endif; ?>
</div>
</div>
<?php if ($node_contents): ?>
<div id="nodecontent">
<?php
$i=1;
foreach ($node_contents as $c) {
	$content_text_text='';
	$content_text_eval=false;
	$content_infile_path=false;
	$content_download_name=$content_download_path=false;
	$content_file_path=$content_file_format=$content_file_lineno=false;
	$content_file_start=$content_file_end=0;
	$content_youtube_id=false;
	$content_youtube_width=$content_youtube_height=0;
	$content_youtube_miniature=$content_youtube_title=false;
	$content_youtube_autoplay=$content_youtube_controls=$content_youtube_fs=$content_youtube_rel=false;
	$content_longtail_file=$content_longtail_image=false;
	$content_longtail_width=$content_longtail_height=0;
	$content_longtail_skin=false;
	$content_longtail_controlbar='none';
	$content_longtail_icons=false;
	$content_longtail_duration=0;
	$content_longtail_autostart=$content_longtail_repeat=false;
	extract($c);	/* content_id content_number content_ignored content_type ... */
?>
<div class="form-group form-inline-auto <?php echo $content_ignored ? 'bg-ignored' : (($i % 2) ? 'bg-odd' : 'bg-even'); ?>">
<input name="content_id[<?php echo $i; ?>]" type="hidden" value="<?php echo $content_id; ?>"/>
<input type="text" class="form-control" name="content_p[<?php echo $i; ?>]" size="2" maxlength="3" value="<?php if ($content_pos): ?><?php echo htmlspecialchars($content_pos, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
<div class="checkbox-inline"><label><input name="content_ignored[<?php echo $i; ?>]" type="checkbox"<?php if ($content_ignored): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_ignored">ignored</span></label></div>
<?php $types=array('text' => 'Text', 'infile' => 'Insertion', 'download' => 'Download','file' => 'File', 'youtube' => 'YouTube', 'longtail' => 'Longtail'); ?>
<span class="form-control-static"><strong><?php echo $types[$content_type]; ?></strong></span>
</div>
<?php switch ($content_type): ?>
<?php case 'text': ?>
<div class="tagbar">
<span class="form-control-static">
<span class="btn_edit btn_p" title="p" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;p&gt;','&lt;/p&gt;')">&lt;p&gt;</span>
<span class="btn_edit btn_b" title="b" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;b&gt;','&lt;/b&gt;')">&lt;b&gt;</span>
<span class="btn_edit btn_i" title="i" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;i&gt;','&lt;/i&gt;')">&lt;i&gt;</span>
<span class="btn_edit btn_u" title="u" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;u&gt;','&lt;/u&gt;')">&lt;u&gt;</span>
<span class="btn_edit btn_s" title="s" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;s&gt;','&lt;/s&gt;')">&lt;s&gt;</span>
<span class="btn_edit btn_h4" title="h4" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;h4&gt;','&lt;/h4&gt;')">&lt;h4&gt;</span>
<span class="btn_edit btn_h5" title="h5" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;h5&gt;','&lt;/h5&gt;')">&lt;h5&gt;</span>
<span class="btn_edit btn_h6" title="h6" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;h6&gt;','&lt;/h6&gt;')">&lt;h6&gt;</span>
<span class="btn_edit btn_br" title="br" onclick="addtag('content_text_text_<?php echo $i; ?>', '','&lt;br /&gt;\n')">&lt;br /&gt;</span>
<span class="btn_edit btn_ol" title="ol" onclick="addtag('content_text_text_<?php echo $i; ?>', '','&lt;ol&gt;\n&lt;li&gt;&lt;/li&gt;\n&lt;/ol&gt;\n')">&lt;ol&gt;</span>
<span class="btn_edit btn_ul" title="ul" onclick="addtag('content_text_text_<?php echo $i; ?>', '','&lt;ul&gt;\n&lt;li&gt;&lt;/li&gt;\n&lt;/ul&gt;\n')">&lt;ul&gt;</span>
<span class="btn_edit btn_table" title="table" onclick="addtag('content_text_text_<?php echo $i; ?>', '','&lt;table&gt;\n&lt;tbody&gt;\n&lt;tr&gt;\n&lt;td&gt;&lt;/td&gt;\n&lt;/tr&gt;\n&lt;/tbody&gt;\n&lt;/table&gt;\n')">&lt;table&gt;</span>
<span class="btn_edit btn_code" title="code" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;code&gt;','&lt;/code&gt;')">&lt;code&gt;</span>
<span class="btn_edit btn_precode" title="pre code" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;pre&gt;&lt;code&gt;','&lt;/code&gt;&lt;/pre&gt;')">&lt;pre&gt;&lt;code&gt;</span>
<span class="btn_edit btn_blockquote" title="blockquote" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;blockquote&gt;','&lt;/blockquote&gt;')">&lt;blockquote&gt;</span>
<span class="btn_edit btn_img" title="img" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;img src=\x22','\x22 alt=\x22\x22 title=\x22\x22 /&gt;')">&lt;img&gt;</span>
<span class="btn_edit btn_a" title="a" onclick="addtag('content_text_text_<?php echo $i; ?>', '&lt;a href=\x22#\x22&gt;','&lt;/a&gt;')">&lt;a&gt;</span>
<span class="btn_edit btn_entquote" title="entquote" onclick="entquote('content_text_text_<?php echo $i; ?>')">entquote</span>
<span class="btn_edit btn_striptags" title="striptags" onclick="striptags('content_text_text_<?php echo $i; ?>')">striptags</span>
</span>
<span class="checkbox-inline">
<input name="content_text_eval[<?php echo $i; ?>]" type="checkbox"<?php if ($content_text_eval): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_seval" title="seval">PHP</span>
</span>
</div>
<div class="form-group form-inline-auto">
<?php $ncols=100; $nrows=min(10, max(4, substr_count(wordwrap($content_text_text, $ncols), "\n")+1));?>
<textarea class="form-control monospace" id="content_text_text_<?php echo $i; ?>" name="content_text_text[<?php echo $i; ?>]" cols="<?php echo $ncols; ?>" rows="<?php echo $nrows; ?>"><?php if ($content_text_text): ?><?php echo htmlspecialchars($content_text_text, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?></textarea>
</div>
<?php break; ?>
<?php case 'infile': ?>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_infile_path[<?php echo $i; ?>]" size="30" maxlength="200" placeholder="File" value="<?php if ($content_infile_path): ?><?php echo htmlspecialchars($content_infile_path, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
<?php break; ?>
<?php case 'download': ?>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_download_name[<?php echo $i; ?>]" size="20" maxlength="50" placeholder="Name" value="<?php if ($content_download_name): ?><?php echo htmlspecialchars($content_download_name, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_download_path[<?php echo $i; ?>]" size="30" maxlength="200" placeholder="File" value="<?php if ($content_download_path): ?><?php echo htmlspecialchars($content_download_path, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
</div>
<?php break; ?>
<?php case 'file': ?>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_file_path[<?php echo $i; ?>]" size="30" maxlength="200" placeholder="File" value="<?php if ($content_file_path): ?><?php echo htmlspecialchars($content_file_path, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_file_start[<?php echo $i; ?>]" size="5" maxlength="5" placeholder="Start" value="<?php if ($content_file_start): ?><?php echo htmlspecialchars($content_file_start, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
<input type="text" class="form-control" name="content_file_end[<?php echo $i; ?>]" size="5" maxlength="5" placeholder="End" value="<?php if ($content_file_end): ?><?php echo htmlspecialchars($content_file_end, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_file_format[<?php echo $i; ?>]" size="10" maxlength="20" placeholder="Format" value="<?php if ($content_file_format): ?><?php echo htmlspecialchars($content_file_format, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
<div class="checkbox-inline">
<label><input name="content_file_lineno[<?php echo $i; ?>]" type="checkbox"<?php if ($content_file_lineno): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_number" title="Number">number</span></label>
</div>
</div>
</div>
<?php break; ?>
<?php case 'youtube': ?>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_youtube_id[<?php echo $i; ?>]" size="11" maxlength="20" placeholder="Id" value="<?php if ($content_youtube_id): ?><?php echo htmlspecialchars($content_youtube_id, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_youtube_width[<?php echo $i; ?>]" size="5" maxlength="5" placeholder="Width" value="<?php if ($content_youtube_width): ?><?php echo htmlspecialchars($content_youtube_width, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
<span class="form-control-static">x</span>
<input type="text" class="form-control" name="content_youtube_height[<?php echo $i; ?>]" size="5" maxlength="5" placeholder="Height" value="<?php if ($content_youtube_height): ?><?php echo htmlspecialchars($content_youtube_height, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
<div class="checkbox-inline">
<label><input name="content_youtube_autoplay[<?php echo $i; ?>]" type="checkbox"<?php if ($content_youtube_autoplay): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_autoplay" title="Auto">auto</span></label>
</div>
</div>
<div class="form-group form-inline-auto">
<select class="form-control" name="content_youtube_theme[<?php echo $i; ?>]" size="1" title="Theme">
<?php foreach (array('dark' => 'dark', 'light' => 'light') as $tm => $ts): ?>
<option value="<?php echo $tm; ?>"<?php if ($content_youtube_theme == $tm) : ?> selected="selected"<?php endif; ?>><?php echo $ts; ?></option>
<?php endforeach; ?>
</select>
<div class="checkbox-inline">
<label><input name="content_youtube_controls[<?php echo $i; ?>]" type="checkbox"<?php if ($content_youtube_controls): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_controls" title="Controls">controls</span></label>
</div>
<div class="checkbox-inline">
<label><input name="content_youtube_fs[<?php echo $i; ?>]" type="checkbox"<?php if ($content_youtube_fs): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_fs" title="Full screen">fs</span></label>
</div>
<div class="checkbox-inline">
<label><input name="content_youtube_rel[<?php echo $i; ?>]" type="checkbox"<?php if ($content_youtube_rel): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_rel" title="Links">links</span></label>
</div>
</div>
</div>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_youtube_miniature[<?php echo $i; ?>]" size="30" maxlength="200" placeholder="Miniature" value="<?php if ($content_youtube_miniature): ?><?php echo htmlspecialchars($content_youtube_miniature, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" />
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_youtube_title[<?php echo $i; ?>]" size="30" maxlength="200" placeholder="Title" value="<?php if ($content_youtube_title): ?><?php echo htmlspecialchars($content_youtube_title, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" />
</div>
</div>
<?php break; ?>
<?php case 'longtail': ?>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_longtail_file[<?php echo $i; ?>]" size="30" maxlength="200" placeholder="File" value="<?php if ($content_longtail_file): ?><?php echo htmlspecialchars($content_longtail_file, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_longtail_width[<?php echo $i; ?>]" size="5" maxlength="5" placeholder="Width" value="<?php if ($content_longtail_width): ?><?php echo htmlspecialchars($content_longtail_width, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)"/>
<span class="form-control-static">x</span>
<input type="text" class="form-control" name="content_longtail_height[<?php echo $i; ?>]" size="5" maxlength="5" placeholder="Height" value="<?php if ($content_longtail_height): ?><?php echo htmlspecialchars($content_longtail_height, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
<div class="form-group form-inline-auto">
<span class="form-control-static">&rarr;</span>
<input type="text" class="form-control" name="content_longtail_duration[<?php echo $i; ?>]" size="5" maxlength="5" placeholder="Duration" value="<?php if ($content_longtail_duration): ?><?php echo htmlspecialchars($content_longtail_duration, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
<div class="checkbox-inline">
<label><input name="content_longtail_autostart[<?php echo $i; ?>]" type="checkbox"<?php if ($content_longtail_autostart): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_autostart" title="Auto">auto</span></label>
</div>
<div class="checkbox-inline">
<label><input name="content_longtail_repeat[<?php echo $i; ?>]" type="checkbox"<?php if ($content_longtail_repeat): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_repeat" title="Loop">loop</span></label>
</div>
</div>
</div>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_longtail_image[<?php echo $i; ?>]" size="30" maxlength="200" placeholder="Picture" value="<?php if ($content_longtail_image): ?><?php echo htmlspecialchars($content_longtail_image, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
<div class="form-group form-inline-auto">
<div class="checkbox-inline">
<label><input name="content_longtail_icons[<?php echo $i; ?>]" type="checkbox"<?php if ($content_longtail_icons): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_playicon" title="Icons">icons</span></label>
</div>
</div>
</div>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="content_longtail_skin[<?php echo $i; ?>]" size="30" maxlength="200" placeholder="Skin" value="<?php if ($content_longtail_skin): ?><?php echo htmlspecialchars($content_longtail_skin, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return returnonenter(event)" />
</div>
<div class="form-group form-inline-auto">
<select class="form-control" name="content_longtail_controlbar[<?php echo $i; ?>]" size="1" title="Control bar">
<?php foreach (array('none' => 'none', 'over' => 'over', 'top' => 'top', 'bottom' => 'bottom') as $cb => $tr): ?>
<option value="<?php echo $cb; ?>"<?php if ($content_longtail_controlbar == $cb) : ?> selected="selected"<?php endif; ?>><?php echo $tr; ?></option>
<?php endforeach; ?>
</select>
</div>
</div>
<?php break; ?>
<?php endswitch; ?>
<?php
	$i++;
}
?>
<div class="form-group">
<button type="submit" class="btn <?php if ($bad_contents): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="content_modify" id="content_modify">Modify</button>
<span class="form-control-static">contents</span>
</div>
</div>
<?php endif; ?>
</form>
<?php head('javascript', 'js.cookie'); ?>
<script>
if (Cookies.get('hidenodecontent') == 1) {
	$('#nodecontent').hide();
}
$('#nodecontent_hidy').click(function() {
	$('#nodecontent').toggle();
	Cookies.set('hidenodecontent', $('#nodecontent').is(':hidden') ? 1 : 0, { path: '/', sameSite: 'lax' });
});
</script>
<?php
$focus=false;
if ($bad_new_content_number) {
	 $focus='#content_new_number';
}
else if ($missing_old_content_number or $bad_old_content_number) {
	 $focus='#content_old_number';
}
?>
<?php if ($focus): ?>
<?php head('javascript', 'jquery.scrollTo', 'screen'); ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus(); $.scrollTo('<?php echo $focus; ?>', {offset: -200}); });
</script>
<?php endif; ?>
<?php endif; ?>
