<?php

/**
 *
 * @copyright  2010-2022 (2016-2022) izend.org
 * @version    21 (4)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<h3><?php echo htmlspecialchars($site_title ? $site_title : $sitename, ENT_COMPAT, 'UTF-8'); ?></h3>
<form method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<?php if ($confirm_delete_thread): ?>
<input name="old_thread_number" type="hidden" value="<?php echo $old_thread_number; ?>" />
<?php endif; ?>
<div class="form-group">
<?php echo $inlanguages; ?>
</div>
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn <?php if ($missing_new_thread_title or $missing_new_thread_name or $bad_new_thread_name or $bad_new_thread_number): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="thread_create" id="thread_create">Add</button>
<span class="form-control-static">thread</span>
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="new_thread_title" id="new_thread_title" size="30" maxlength="100" placeholder="Title" value="<?php if ($new_thread_title): ?><?php echo htmlspecialchars($new_thread_title, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return focusonenter(event, 'new_thread_number')" />
</div>
<div class="form-group form-inline-auto">
<span class="form-control-static">#</span>
<input type="text" class="form-control" name="new_thread_number" id="new_thread_number" size="2" maxlength="3" value="<?php if ($new_thread_number): ?><?php echo htmlspecialchars($new_thread_number, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return submitonenter(event, 'thread_create')" />
<span class="form-control-static">type</span>
<select class="form-control" name="new_thread_type" size="1">
<option value="thread"<?php if ($new_thread_type == 'thread'): ?> selected="selected"<?php endif; ?>>Thread</option>
<?php foreach ($supported_threads as $type): ?>
<?php if ($type == 'folder'): ?>
<option value="folder"<?php if ($new_thread_type == 'folder'): ?> selected="selected"<?php endif; ?>>Folder</option>
<?php elseif ($type == 'story'): ?>
<option value="story"<?php if ($new_thread_type == 'story'): ?> selected="selected"<?php endif; ?>>Article</option>
<?php elseif ($type == 'book'): ?>
<option value="book"<?php if ($new_thread_type == 'book'): ?> selected="selected"<?php endif; ?>>Manual</option>
<?php elseif ($type == 'rss'): ?>
<option value="rss"<?php if ($new_thread_type == 'rss'): ?> selected="selected"<?php endif; ?>>RSS</option>
<?php elseif ($type == 'newsletter'): ?>
<option value="newsletter"<?php if ($new_thread_type == 'newsletter'): ?> selected="selected"<?php endif; ?>>Newsletter</option>
<?php endif; ?>
<?php endforeach; ?>
</select>
</div>
</div>
<?php if ($thread_list): ?>
<fieldset>
<legend>Catalog</legend>
<div class="form-group">
<?php
foreach ($thread_list as $i => $tr):
	extract($tr);	/* pos, thread_id, thread_title, thread_number, thread_url */
	$thread_url .= '?' . 'clang=' . $clang;
?>
<div class="form-group form-inline">
<div class="form-group form-inline-auto">
<input type="text" class="form-control input-sm" name="p[<?php echo $i; ?>]" size="2" maxlength="3" value="<?php echo $pos; ?>" onkeypress="return returnonenter(event)" />
</div>
<span class="form-control-static">
<a href="<?php echo $thread_url; ?>" title="<?php echo $thread_id; ?>"><?php echo $thread_title ? htmlspecialchars($thread_title, ENT_COMPAT, 'UTF-8') : $thread_id; ?></a>
</span>
</div>
<?php endforeach; ?>
</div>
</fieldset>
<?php if ($confirm_delete_thread): ?>
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn btn-default" name="thread_canceldelete" id="thread_canceldelete">Cancel</button>
<span class="form-control-static">or</span>
<button type="submit" class="btn btn-warning" name="thread_confirmdelete" id="thread_confirmdelete">Confirm</button>
</div>
<div class="form-group">
<span class="form-control-static">deleting thread <strong><?php echo $old_thread_number; ?></strong></span>
</div>
</div>
<?php else: ?>
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn btn-default" name="threadlist_reorder" id="threadlist_reorder">Sort</button>
<span class="form-control-static">contents or</span>
</div>
<div class="form-group form-inline-auto">
<button type="submit" class="btn <?php if ($missing_old_thread_number or $bad_old_thread_number): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="thread_delete" id="thread_delete">Delete</button>
<span class="form-control-static">thread #</span>
<input type="text" class="form-control" name="old_thread_number" id="old_thread_number" size="2" maxlength="3" placeholder="" value="<?php if ($old_thread_number): ?><?php echo htmlspecialchars($old_thread_number, ENT_COMPAT, 'UTF-8'); ?><?php endif; ?>" onkeypress="return submitonenter(event, 'thread_delete')" />
</div>
</div>
<?php endif; ?>
<?php endif; ?>
</form>
<?php
$focus=false;
if ($missing_new_thread_title or $missing_new_thread_name or $bad_new_thread_name) {
	 $focus='#new_thread_title';
}
else if ($bad_new_thread_number) {
	$focus='#new_thread_number';
}
else if ($missing_old_thread_number or $bad_old_thread_number) {
	$focus='#old_thread_number';
}
else if ($confirm_delete_thread) {
	$focus='#old_thread_number';
}
?>
<?php if ($focus): ?>
<?php head('javascript', 'jquery.scrollTo', 'screen'); ?>
<script>
$(function() {$('<?php echo $focus; ?>').focus(); $.scrollTo('<?php echo $focus; ?>', {offset: -200}); });
</script>
<?php endif; ?>
