<?php

/**
 *
 * @copyright  2010-2015 (2016) izend.org
 * @version    29 (2)
 * @link       http://www.izend.org
 */
?>
<?php extract($errors); ?>
<h3<?php if ($thread_title): ?> title="<?php echo $thread_id; ?>"<?php endif; ?>><?php echo htmlspecialchars($thread_title ? $thread_title : $thread_id, ENT_COMPAT, 'UTF-8'); ?></h3>
<form method="post">
<input name="clang" type="hidden" value="<?php echo $clang; ?>" />
<span id="thread_hidy" class="hidy"></span>
<div class="form-group">
<?php echo $inlanguages; ?>
</div>
<div id="thread">
<div class="form-group<?php if ($missing_new_node_title or $bad_new_node_title): ?> has-error<?php endif; ?>">
<label for="thread_title">Title</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="thread_title" id="thread_title" size="40" maxlength="100" value="<?php echo htmlspecialchars($thread_title, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'thread_edit')"/>
</div>
</div>
<div class="form-group<?php if ($missing_thread_name or $bad_thread_name): ?> has-error<?php endif; ?>">
<label for="thread_name">URL</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="thread_name" id="thread_name" size="40" maxlength="100" value="<?php echo htmlspecialchars($thread_name, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'thread_edit')"/>
</div>
</div>
<div class="form-group">
<label for="thread_abstract">Abstract</label>
<div class="form-inline-auto">
<textarea class="form-control" name="thread_abstract" id="thread_abstract" cols="80" rows="3"><?php echo htmlspecialchars($thread_abstract, ENT_COMPAT, 'UTF-8'); ?></textarea>
</div>
</div>
<div class="form-group">
<label for="thread_cloud">Cloud</label>
<div class="form-inline-auto">
<textarea class="form-control" name="thread_cloud" id="thread_cloud" cols="80" rows="2"><?php echo htmlspecialchars($thread_cloud, ENT_COMPAT, 'UTF-8'); ?></textarea>
</div>
</div>
<div class="form-group">
<label for="thread_image">Image</label>
<div class="form-inline-auto">
<input type="text" class="form-control" name="thread_image" id="thread_image" size="40" maxlength="200" value="<?php echo htmlspecialchars($thread_image, ENT_COMPAT, 'UTF-8'); ?>"/>
</div>
</div>
<div class="form-group form-inline-auto">
<label for="thread_type">Type</label>
<select class="form-control" name="thread_type" size="1">
<option value="thread"<?php if ($thread_type == 'thread'): ?> selected="selected"<?php endif; ?>>Thread</option>
<?php foreach ($supported_threads as $type): ?>
<?php if ($type == 'folder'): ?>
<option value="folder"<?php if ($thread_type == 'folder'): ?> selected="selected"<?php endif; ?>>Folder</option>
<?php elseif ($type == 'story'): ?>
<option value="story"<?php if ($thread_type == 'story'): ?> selected="selected"<?php endif; ?>>Article</option>
<?php elseif ($type == 'book'): ?>
<option value="book"<?php if ($thread_type == 'book'): ?> selected="selected"<?php endif; ?>>Manual</option>
<?php elseif ($type == 'rss'): ?>
<option value="rss"<?php if ($thread_type == 'rss'): ?> selected="selected"<?php endif; ?>>RSS</option>
<?php elseif ($type == 'newsletter'): ?>
<option value="newsletter"<?php if ($thread_type == 'newsletter'): ?> selected="selected"<?php endif; ?>>Newsletter</option>
<?php endif; ?>
<?php endforeach; ?>
</select>
</div>
<fieldset>
<legend>Options</legend>
<div class="form-group form-inline">
<div class="form-group checkbox-group">
<div class="checkbox-inline">
<label for="thread_search"><input id="thread_search" name="thread_search" type="checkbox"<?php if ($thread_search): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_search">search</span></label>
</div>
<div class="checkbox-inline">
<label for="thread_tag"><input id="thread_tag" name="thread_tag" type="checkbox"<?php if ($thread_tag): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_tag">cloud</span></label>
</div>
<div class="checkbox-inline">
<label for="thread_visits"><input id="thread_visits" name="thread_visits" type="checkbox"<?php if ($thread_visits): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_visits">visits</span></label>
</div>
</div>
<div class="form-group checkbox-group">
<div class="checkbox-inline">
<label for="thread_comment"><input id="thread_comment" name="thread_comment" type="checkbox"<?php if ($thread_comment): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_comment">comment</span></label>
</div>
<div class="checkbox-inline">
<label for="thread_morecomment"><input id="thread_morecomment" name="thread_morecomment" type="checkbox"<?php if ($thread_morecomment): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_morecomment">comment+</span></label>
</div>
<div class="checkbox-inline">
<label for="thread_vote"><input id="thread_vote" name="thread_vote" type="checkbox"<?php if ($thread_vote): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_vote">vote</span></label>
</div>
<div class="checkbox-inline">
<label for="thread_morevote"><input id="thread_morevote" name="thread_morevote" type="checkbox"<?php if ($thread_morevote): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_morevote">vote+</span></label>
</div>
</div>
<div class="form-group checkbox-group">
<div class="checkbox-inline">
<label for="thread_ilike"><input id="thread_ilike" name="thread_ilike" type="checkbox"<?php if ($thread_ilike): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_ilike">facebook</span></label>
</div>
<div class="checkbox-inline">
<label for="thread_tweet"><input id="thread_tweet" name="thread_tweet" type="checkbox"<?php if ($thread_tweet): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_tweet">twitter</span></label>
</div>
<div class="checkbox-inline">
<label for="thread_plusone"><input id="thread_plusone" name="thread_plusone" type="checkbox"<?php if ($thread_plusone): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_plusone">google+</span></label>
</div>
<div class="checkbox-inline">
<label for="thread_linkedin"><input id="thread_linkedin" name="thread_linkedin" type="checkbox"<?php if ($thread_linkedin): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_linkedin">linkedin</span></label>
</div>
<div class="checkbox-inline">
<label for="thread_pinit"><input id="thread_pinit" name="thread_pinit" type="checkbox"<?php if ($thread_pinit): ?> checked="checked"<?php endif; ?> /><span class="btn_edit btn_pinit">pinit</span></label>
</div>
</div>
</div>
</fieldset>
<div class="form-group">
<button type="submit" class="btn <?php if ($missing_thread_name or $bad_thread_name or $missing_thread_type or $bad_thread_type): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="thread_edit" id="thread_edit">Edit</button>
</div>
</div>
<h4>Contents</h4>
<?php if ($thread_contents): ?>
<span id="threadcontent_hidy" class="hidy"></span>
<?php endif; ?>
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn <?php if ($missing_new_node_title or $bad_new_node_title or $bad_new_node_number): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="node_create" id="node_create">Add</button>
<span class="form-control-static">content</span>
</div>
<div class="form-group form-inline-auto">
<input type="text" class="form-control" name="new_node_title" id="new_node_title" size="30" maxlength="100" placeholder="Title" value="<?php echo htmlspecialchars($new_node_title, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return focusonenter(event, 'new_node_number')" />
</div>
<div class="form-group form-inline-auto">
<span class="form-control-static">#</span>
<input type="text" class="form-control" name="new_node_number" id="new_node_number" size="2" maxlength="3" value="<?php echo htmlspecialchars($new_node_number, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'node_create')" />
</div>
</div>
<?php if ($thread_contents): ?>
<div id="threadcontent">
<fieldset class="block">
<legend>Summary</legend>
<div class="form-group">
<?php
$i=1;
$maxlen=strlen(count($thread_contents))+1;
foreach ($thread_contents as $c):
	extract($c);	/* pos, node_id, node_title, node_url, node_number, node_ignored */
	$node_url .= '?' . 'clang=' . $clang;
?>
<div class="form-group form-inline <?php if ($node_ignored): ?> bg-ignored<?php endif; ?>">
<div class="form-group form-inline-auto">
<input type="text" class="form-control input-sm" name="p[<?php echo $i; ?>]" size="2" maxlength="<?php echo $maxlen; ?>" value="<?php echo $pos; ?>" />
</div>
<span class="form-control-static">
<a href="<?php echo $node_url; ?>" title="<?php echo $node_id; ?>"><?php echo $node_title ? htmlspecialchars($node_title, ENT_COMPAT, 'UTF-8') : $node_id; ?></a>
</span>
</div>
<?php $i++; ?>
<?php endforeach; ?>
</div>
</fieldset>
<?php if ($confirm_delete_node): ?>
<input name="old_node_number" type="hidden" value="<?php echo $old_node_number; ?>" />
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn btn-default" name="node_canceldelete" id="node_canceldelete">Cancel</button>
<span class="form-control-static">or</span>
<button type="submit" class="btn btn-warning" name="node_confirmdelete" id="node_confirmdelete">Confirm</button>
</div>
<div class="form-group">
<span class="form-control-static">deleting content <strong><?php echo $old_node_number; ?></strong></span>
</div>
</div>
<?php else: ?>
<div class="form-group form-inline">
<div class="form-group">
<button type="submit" class="btn btn-default" name="thread_reorder" id="thread_reorder">Sort</button>
<span class="form-control-static">thread or</span>
</div>
<div class="form-group form-inline">
<button type="submit" class="btn <?php if ($missing_old_node_number or $bad_old_node_number): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="node_hide" id="node_hide">Hide</button>
<button type="submit" class="btn <?php if ($missing_old_node_number or $bad_old_node_number): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="node_show" id="node_show">Show</button>
<button type="submit" class="btn <?php if ($missing_new_node_title or $bad_new_node_title or $bad_new_node_number): ?>btn-danger<?php else: ?>btn-default<?php endif; ?>" name="node_copy" id="node_copy">Copy</button>
<button type="submit" class="btn <?php if ($missing_old_node_number or $bad_old_node_number): ?>btn-danger<?php elseif ($confirm_delete_node): ?>btn-warning<?php else: ?>btn-default<?php endif; ?>" name="node_delete" id="node_delete">Delete</button>
</div>
<div class="form-group form-inline-auto">
<span class="form-control-static">content #</span>
<input type="text" class="form-control" name="old_node_number" id="old_node_number" size="2" maxlength="3" placeholder="" value="<?php echo htmlspecialchars($old_node_number, ENT_COMPAT, 'UTF-8'); ?>" onkeypress="return submitonenter(event, 'node_delete')" />
</div>
</div>
<?php endif; ?>
<?php endif; ?>
</div>
</form>
<?php head('javascript', 'jquery.cookie'); ?>
<script type="text/javascript">
if ($.cookie('hidethread') == 1) {
	$('#thread').hide();
}
$('#thread_hidy').click(function() {
	$('#thread').toggle();
	$.cookie('hidethread', $('#thread').is(':hidden') ? 1 : 0, { path: '/' });
});
</script>
<?php if ($thread_contents): ?>
<script type="text/javascript">
if ($.cookie('hidethreadcontent') == 1) {
	$('#threadcontent').hide();
}
$('#threadcontent_hidy').click(function() {
	$('#threadcontent').toggle();
	$.cookie('hidethreadcontent', $('#threadcontent').is(':hidden') ? 1 : 0, { path: '/' });
});
</script>
<?php endif; ?>
<?php
$focus=false;
if ($missing_thread_name or $bad_thread_name) {
	$focus='#thread_name';
}
else if ($missing_new_node_title or $bad_new_node_title) {
	$focus='#new_node_title';
}
else if ($bad_new_node_number) {
	$focus='#new_node_number';
}
else if ($missing_old_node_number or $bad_old_node_number) {
	$focus='#old_node_number';
}
else if ($confirm_delete_node) {
	$focus='#old_node_number';
}
?>
<?php if ($focus): ?>
<?php head('javascript', 'jquery.scrollTo', 'screen'); ?>
<script type="text/javascript">
$(function() {$('<?php echo $focus; ?>').focus(); $.scrollTo('<?php echo $focus; ?>', {offset: -200}); });
</script>
<?php endif; ?>
